const RESTRICTED_JET_MISSION_TYPES = ["A319", "E190", "E195", "RJ70", "RJ85", "RJ1H", "RJ1F", "B461", "B462", "B462_QT", "B463", "B463_QT"];
const EGLC_JET_MISSION_TYPES = RESTRICTED_JET_MISSION_TYPES.concat(["F70"]);
const REGIONAL_JET_FREIGHTERS = ["B462_QT", "B463_QT", "RJ1F"];
const MAINLINE_JET_FREIGHTERS = ["B738_BCF", "B738_BDSF", "B72F"];
const SMALL_GA_TRAINERS = ["PA28", "P28A", "PA38"];
const VULCAN_RECON_PREFERRED = ["VULC"];
const TACTICAL_JET_MISSION_TYPES = ["F14A", "F14B", "HAWK", "JAGR", "TOR"];
const STRATEGIC_RECON_AIRCRAFT = ["VULC", "C160", "C130", "P38", "SPIT", "BF109", "F6F", "FW08", "A6M5"].concat(TACTICAL_JET_MISSION_TYPES);
const CELEBRITY_BIZ_JET_PREFERRED = ["STAR", "P180", "C700", "C680", "C750", "E55P", "FA50", "LJ35", "HDJT", "SF50"];
const CELEBRITY_VIP_SCENARIO_WEIGHT_MULT = 5;

// Military airlifters (CIVIL_OK): civilian heavy-freight scenarios only — military templates unchanged.
const MIL_AIRLIFTER_CIVIL_TYPES = ["A400", "C130", "C160"];
const MIL_AIRLIFTER_CIVIL_BASE_SCENARIO_IMGIDS = [104, 110, 111, 115, 116, 120, 121, 122, 123];
const MIL_AIRLIFTER_CIVIL_EXTRA_SCENARIO_BY_TYPE = { C160: [114] };
const MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT = ["A400", "C130", "C160"];
const MIL_AIRLIFTER_EXCLUDED_OVERNIGHT_PARCELS = ["A400", "C130"];
function getMilAirlifterCivilScenarioImgIds(aircraftType) {
    if (!MIL_AIRLIFTER_CIVIL_TYPES.includes(aircraftType)) return null;
    const extra = MIL_AIRLIFTER_CIVIL_EXTRA_SCENARIO_BY_TYPE[aircraftType] || [];
    return MIL_AIRLIFTER_CIVIL_BASE_SCENARIO_IMGIDS.concat(extra);
}
// Back-compat alias for audits referencing the A400 base list.
const A400_CIVIL_FREIGHT_SCENARIO_IMGIDS = MIL_AIRLIFTER_CIVIL_BASE_SCENARIO_IMGIDS;

const missionMatrix = [
    // UNIQUE MISSION TEMPLATES — one mission (imgId) each via pool "uniqueMissions"
    { type: 1, name: "Noise Abatement Departure (EGLC)", detail: "Execute a steep climb out of EGLC.", pool: "uniqueMissions", weight: 1,  requiredDep: "EGLC", allowedAircraft: EGLC_JET_MISSION_TYPES, maxMTOW: 75500 },
    { type: 2, name: "Noise Abatement Departure (EGNS)", detail: "Execute a steep climb out of EGNS.", pool: "uniqueMissions", weight: 1, requiredDep: "EGNS", allowedAircraft: RESTRICTED_JET_MISSION_TYPES, maxMTOW: 75500 },
    { type: 3, name: "Ponte Aérea Commuter", detail: "Departing SBRJ requires precision due to the short runway and surrounding terrain. Utilize maximum takeoff thrust and be prepared for an immediate tight climbing turn after rotation.", pool: "uniqueMissions", weight: 1, requiredDep: "SBRJ", allowedAircraft: ["A319", "E190", "E195"], maxMTOW: 75500 },
    { type: 4, name: "Classic Cross-Country Rally", detail: "Pushing the Comanche to its cruise limits today. Monitor your cylinder head temperatures and carefully manage your mixture to optimize fuel burn for the rally.", pool: "uniqueMissions", weight: 1, allowedAircraft: ["PA24"] },
	{ type: 5, name: "High-Altitude Express", detail: "Take advantage of the aircraft's pressurization and climb rate to get above the regional weather systems. Keep your block time tight.", pool: "uniqueMissions", weight: 1, minAlt: 10000, rules: "IFR", allowedAircraft: ["C414", "B58T", "BE60", "STAR", "P180", "TBM8"] },
    { type: 7,  name: "Whisperjet Operations", detail: "Your airframe was picked specifically for its quiet acoustic footprint. Adhere strictly to the descent profile and avoid late configuration changes.", pool: "uniqueMissions", weight: 1, allowedAircraft: ["RJ1F", "B462_QT", "B463_QT", "B462_MIL"] },
    { type: 8,  name: "Research Observation Flight", detail: "A local university needs optical data on changing topography. Maintain a steady track at low altitudes. Monitor your radial engine temperatures carefully.", pool: "uniqueMissions", weight: 40, allowedAircraft: ["U16"] },
    { type: 9,  name: "Remote Outpost Resupply", detail: "You're utilizing the Albatross's heavy lift capacity and rugged landing gear today. Execute a standard approach, but be mindful of the heavy control inputs required for this vintage airframe.", pool: "uniqueMissions", weight: 40, allowedAircraft: ["U16"] },
    { type: 10, name: "Albatross Patrol Run", detail: "Flying a patrol route. Keep your eyes outside the cockpit, maintain visual contact with the terrain where possible, and execute smooth turns.", pool: "uniqueMissions", weight: 40, allowedAircraft: ["U16"] },
    { type: 11, name: "Survey Platform", detail: "A local university needs optical data on changing topography. Maintain a steady track at low altitudes. Monitor your radial engine temperatures carefully.", pool: "uniqueMissions", weight: 40, allowedAircraft: ["U16"] },
    { type: 12, name: "Remote Supply Drop", detail: "You're utilizing the Albatross's heavy lift capacity and rugged landing gear today. Execute a standard approach, but be mindful of the heavy control inputs required for this vintage airframe.", pool: "uniqueMissions", weight: 40, allowedAircraft: ["U16"] },
    { type: 13, name: "Commemorative SAR Demo", detail: "Flying a commemorative SAR route to honor the crews who operated these flying boats. Keep your eyes outside the cockpit, maintain visual contact with the terrain, and execute smooth, sweeping turns.", pool: "uniqueMissions", weight: 40, allowedAircraft: ["U16"] },
    // DYNAMIC MASTER TEMPLATES - no image required
    { type: 14, name: "Commercial Service", pool: "commercial", weight: 15, allowedClasses: ["JET", "TURBO"] },
    { type: 15, name: "Regional Commuter", pool: "commercial-regional", weight: 15, allowedClasses: ["TURBO", "JET"] },
    { type: 16, name: "Executive Charter", pool: "executive", weight: 15, allowedClasses: ["BIZ JET", "TURBO", "HELI"], minPaxSeats: 2, minPaxSeatsAppliesTo: ["HELI"], excludedAircraft: SMALL_GA_TRAINERS.concat(MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT) },
    { type: 17, name: "Light Freight Ops", pool: "lightFreight", weight: 15, allowedClasses: ["GA", "TURBO", "BIZ JET", "JET"], maxMTOW: 5000, maxMTOWAppliesTo: ["GA", "TURBO"], excludedAircraft: MAINLINE_JET_FREIGHTERS },
    { type: 18, name: "Heavy Cargo Transport", pool: "heavyFreight", weight: 15, allowedClasses: ["JET", "TURBO"], minCargo: 2000, excludedAircraft: ["VULC"] },
    { type: 19, name: "Medical Relay", pool: "medical", weight: 15, allowedClasses: ["GA", "TURBO", "HELI", "BIZ JET"] },
    { type: 20, name: "Aerial Survey", pool: "surveyServices", weight: 15, allowedClasses: ["GA", "HELI"], excludedAircraft: ["C700"], maxMTOW: 8000 },
    { type: 21, name: "Rotary Wing Operations", pool: "helicopterOps-CIV", weight: 15, allowedClasses: ["HELI"], civilianOnly: true },
    { type: 22, name: "Local Rotary Wing Operations", pool: "helicopterOps-CIV", weight: 15, allowedClasses: ["HELI"], isLocal: true, civilianOnly: true },
    { type: 23, name: "Tactical Sortie", pool: "tacticalJet-MIL", weight: 15, allowedClasses: ["JET", "WARBIRD", "HELI"], militaryOnly: true, tacticalOnly: true },
    { type: 24, name: "Military Logistics", pool: "militaryTransit-MIL", weight: 15, allowedClasses: ["TURBO", "JET", "HELI", "WARBIRD"], militaryOnly: true },
    { type: 25, name: "Heritage Flight", pool: "vintageOps", weight: 15, allowedClasses: ["WARBIRD", "GA", "TURBO", "JET"] },
    { type: 26, name: "Classic Airliner Charter", pool: "vintageAirliner", weight: 40, allowedAircraft: ["DC6B"], excludedAircraft: ["DC6A"] },
    { type: 27, name: "Weather Ops", pool: "highAltServices", weight: 15, allowedClasses: ["TURBO", "JET"], excludedAircraft: ["C700", "STAR", "P180"] },
    { type: 28, name: "Air Taxi", pool: "lightPax", weight: 15, allowedClasses: ["GA", "TURBO", "BIZ JET", "HELI"], maxMTOW: 6000, maxMTOWAppliesTo: ["GA", "TURBO", "HELI"], excludedAircraft: SMALL_GA_TRAINERS },
    { type: 29, name: "Mil-Cargo Ops", pool: "heavyFreight-MIL", weight: 15, allowedClasses: ["JET", "TURBO", "HELI"], minCargo: 4000, militaryOnly: true, excludedAircraft: ["VULC"] },
    { type: 30, name: "Military Heli-Ops", pool: "helicopterOps-MIL", weight: 15, allowedClasses: ["HELI"], militaryOnly: true },
    { type: 31, name: "Base Staff Shuttle", pool: "helicopterOps-MIL", weight: 15, allowedClasses: ["HELI"], militaryOnly: true, isLocal: true },
    { type: 32, name: "Strategic Recon.", pool: "reconnaissance-MIL", weight: 20, allowedClasses: ["JET", "WARBIRD", "TURBO"], militaryOnly: true },
    { type: 33, name: "Vintage Propliner Freight", detail: "Classic propliner freight for the DC-6A. Keep your RPMs synced, mind the cowl flaps, and remember that descending takes planning when you don't have speedbrakes.", pool: "vintageProplinerFreight", weight: 40, allowedAircraft: ["DC6A"], excludedAircraft: ["DC6B"], minCargo: 2000 },
    { type: 34, name: "Gliding Operations", pool: "gliderOps", allowedClasses: ["GLIDER"], rules: "VFR/Scenic" },
    { type: 39, name: "Regional Freight Pulse", pool: "regionalFreight", weight: 15, allowedClasses: ["JET", "TURBO"] }
];

/** Brief contract-board headline per scenario imgId (from scenario-job-titles.json). */
const SCENARIO_JOB_TITLES = {
    1: "EGLC Steep Climb",
    2: "EGNS Steep Climb",
    3: "Ponte Aérea Special",
    4: "Cross-Country Rally",
    5: "High-Altitude Express",
    7: "Whisperjet Run",
    8: "Geological Research",
    9: "Outpost Resupply",
    10: "Early Patrol Run",
    11: "Survey Platform",
    12: "Remote Supply Drop",
    13: "SAR Operations",
    14: "Sports Team Charter",
    15: "Holiday Charter",
    16: "Passenger Recovery",
    17: "Hub Connector",
    18: "Tourist Transport",
    19: "Tech Convention Ferry",
    20: "Holiday Route",
    21: "Regional System Outage",
    22: "Corporate Summit",
    23: "Flagship Route",
    24: "Scheduled Commercial Sector",
    25: "Standard Commercial Route",
    26: "Business Shuttle",
    27: "Uni Students",
    28: "Symphony Orchestra",
    29: "Exchange Students",
    30: "Company Seminar",
    31: "Championship Final",
    32: "Warmer Climates",
    33: "Regional Hop",
    34: "Regional Sectors",
    35: "Network Support",
    36: "Late-Evening Commuter",
    37: "Weather Groundings",
    38: "Regional Holidays",
    39: "Diversion Recovery",
    40: "Corporate Summit",
    41: "Busy as a bee",
    42: "Hub Feeder",
    43: "Exchange Students",
    44: "Staff Seminar",
    45: "VIP Charter",
    46: "Sports Charter",
    47: "Executive Negotiation",
    48: "Executive Offsite",
    49: "Diplomatic Immunity",
    50: "VIP Conference",
    51: "Exec. Shuttle",
    52: "Share Owner Trip",
    53: "Investor Roadshow",
    54: "Secure Witness Transport",
    55: "Private Buyer",
    56: "Crisis Counsel",
    57: "VIP Feline",
    58: "VIP Charter",
    59: "Weekend Retreat",
    60: "Business Commute",
    61: "VIP Stadium Transport",
    62: "Spiritual Retreat",
    63: "Championship Flight",
    64: "VIP Film Premiere",
    65: "Club Exec. Transport",
    66: "Surgical Team Transport",
    67: "VIP Private Gala",
    68: "Executive Support",
    69: "Patient Airlift",
    70: "Medical Transport",
    71: "Patient Transport",
    72: "Diplomatic Files",
    73: "Prototype Hardware",
    74: "Protected Species",
    75: "Conservation Saplings",
    76: "Digital Masters",
    77: "Rare Manuscripts",
    78: "AOG Component",
    79: "Medical Freight",
    80: "Medical Transport",
    81: "Medical Supplies",
    82: "Farm Produce",
    83: "Regional Overnight",
    84: "Regional Mail",
    85: "Essential Supplies",
    86: "Regional Supplies",
    87: "Regional Lab Samples",
    88: "Morning Papers",
    89: "Premium Seafood",
    90: "Avionics Ferry",
    91: "Rare Component Transport",
    92: "Critical Machinery Parts",
    93: "I want one too!",
    94: "Mail Run",
    95: "Community Supply",
    96: "Night Express",
    97: "Priority Parcels",
    98: "Overnight Freight",
    99: "Medical Freight",
    100: "Lab Samples",
    101: "Critical Machinery Parts",
    102: "Regional Supplies",
    103: "Late Night Regional",
    104: "What a Relief",
    105: "High Street Supplies",
    106: "Museum Artifacts",
    107: "Industrial Hardware",
    108: "Luxury Vehicles",
    109: "Supercar Delivery",
    110: "Oilfield Equipment",
    111: "Avionics Bay",
    112: "Premium Perishables",
    113: "Bulk Perishables",
    114: "Overnight Parcels",
    115: "Secure Bullion",
    116: "Max Payload",
    117: "Overnight Main Deck",
    118: "Amazon and on and on",
    119: "Formula One Chassis",
    120: "Heavy Machinery",
    121: "Industrial Generator",
    122: "Replacement Turbine",
    123: "Server Rack Delivery",
    124: "Misinformation",
    125: "Pipeline Survey",
    126: "Crop Inspection",
    127: "Expansion Zone",
    128: "Subsurface Mapping",
    129: "Storm Assessment",
    130: "LIDAR Assessment",
    131: "High-end property shoot",
    132: "Anomaly Survey",
    133: "Missing Vehicle Search",
    134: "Staff Shuttle",
    135: "Currency Flight",
    136: "Consultant Hop",
    137: "Community Link",
    138: "Private Schedule",
    139: "VIP Spiritual Retreat",
    140: "Romantic twilight flight",
    141: "Missed Connection",
    142: "Family Link",
    143: "Honeymoon Charter",
    144: "Medical Examiner",
    145: "The Gentleman's Estate",
    146: "Ferry Delivery",
    147: "Weather Ops",
    148: "Storm Chasers",
    149: "Airshow Display",
    150: "Handicap Race",
    151: "Vintage Airframe ferry",
    152: "Chase Plane (not that one)",
    153: "Commemorative Fly-by",
    154: "Keeping current",
    155: "Restoration Delivery",
    156: "Aviation Festival",
    157: "Remembrance Flight",
    158: "Vintage Freight",
    159: "Live Agricultural",
    160: "Classic Heavy Lift",
    161: "Pallet Freight",
    162: "Overnight Liner",
    163: "Holiday Liner",
    164: "Executive Extraction",
    165: "Matchday Fans",
    166: "Classic Shuttle",
    167: "Scenic Hop",
    168: "Photo Survey",
    169: "Traffic Watch",
    170: "On-Demand Charter",
    171: "Highway Extraction",
    172: "SAR Ops",
    173: "Aerial Overwatch",
    174: "Property Developers",
    175: "Industrial Support",
    176: "Wildlife Tracking",
    177: "Executive Shuttle",
    178: "Live Event Monitoring",
    179: "Cinematic Tracking Shots",
    180: "Put that in your pipe",
    181: "High Tension Cleaning",
    182: "Sensitive Documents",
    183: "Shiny but what is it?",
    184: "Tactical Vehicle Transport",
    185: "Defense Component Transport",
    186: "Sensitive Hardware",
    187: "Technical Spares",
    188: "AOG Parts for Inspection",
    189: "Tactical Cargo Delivery",
    190: "Refugee Relief Supply",
    191: "Ground Team Deployment",
    192: "Perimeter Survey",
    193: "VIP Base Tour",
    194: "SAR Training",
    195: "Observation Post Resupply",
    196: "Command Briefing",
    197: "Telemetry Transfer",
    198: "Unmarked Containers",
    199: "Relocating Defense Personnel",
    200: "Strategic repositioning",
    201: "Navigation Exercise",
    202: "Tactical Escort",
    203: "Diplomatic Pouch",
    204: "Cryogenic xenobiological tissue transfer",
    205: "SAR Support",
    206: "Surface Anomaly",
    207: "Comms Relay",
    208: "Passive Telemetry",
    209: "Radar Calibration",
    210: "Intercept Profile",
    211: "Cross-Service Exercise",
    212: "Sensor Check",
    213: "Approach Vector Testing",
    214: "Maintenance Ferry",
    215: "Two-Ship Transit",
    216: "Proficiency Check",
    217: "Terrain Masking",
    218: "Red Air Support",
    219: "Festival Ferry",
    220: "Tanker Practice",
    221: "Transit Recon",
    222: "Corridor Mapping",
    223: "Route Photography",
    224: "Cross-Country Task",
    225: "Soaring Currency",
    226: "Lift me up",
    227: "Instructional Sortie",
    228: "Powered Ferry",
    229: "Practice Task",
    249: "Formation Transit",
    250: "Tanker Practice"
};

const scenarioDB = {
    uniqueMissions: [
        { imgId: 1, missionType: 1, payload: "Noise Abatement Departure (EGLC)", instruction: "You have a noise abatement departure out of EGLC today. Fly the steep climb profile and keep it clean for the monitors below." },
        { imgId: 2, missionType: 2, payload: "Noise Abatement Departure (EGNS)", instruction: "You have a noise abatement departure out of EGNS today. Fly the steep climb profile and keep it tight for the community underneath." },
        { imgId: 3, missionType: 3, payload: "Ponte Aérea Commuter", instruction: "You are departing SBRJ on the Ponte Aérea run. Use max thrust, expect a tight climbing turn right after rotation and watch the terrain closely." },
        { imgId: 4, missionType: 4, payload: "Classic Cross-Country Rally", instruction: "You are pushing the Comanche hard on this cross-country rally. Watch your cylinder head temps and manage the mixture so you do not cook the engine on the long legs." },
        { imgId: 5, missionType: 5, payload: "High-Altitude Express", instruction: "You have pressurization and climb rate to work with today. Use both to get above the regional weather and keep your block time tight." },
        { imgId: 7, missionType: 7, payload: "Whisperjet Operations", instruction: "You were picked for this run because the airframe is quiet. Stick to the descent profile and do not leave gear or flaps hanging out late." },
        { imgId: 8,   missionType: 8,  payload: "flying researchers over surface anomalies", instruction: "A local university wants optical data on changing topography below. Hold a steady low track and watch those radial engine temps on the Albatross.", allowedAircraft: ["U16"] },
        { imgId: 9,   missionType: 9,  payload: "delivering bulk provisions to a distant outpost", instruction: "You have bulk provisions for a distant outpost today. The Albatross is heavy and vintage — fly a standard approach and be ready for firm control inputs.", allowedAircraft: ["U16"] },
		{ imgId: 10,  missionType: 10, payload: "Albatross Patrol Run", instruction: "You are on an Albatross patrol run today. Keep your eyes outside, stay in visual contact with the terrain where you can and fly smooth turns.", allowedAircraft: ["U16"] },
        { imgId: 11, missionType: 11, payload: "Survey Platform", instruction: "A local university wants optical data on changing topography below. Hold a steady low track and watch those radial engine temps on the Albatross.", allowedAircraft: ["U16"] },
        { imgId: 12, missionType: 12, payload: "Remote Supply Drop", instruction: "You have bulk provisions for a distant outpost today. The Albatross is heavy and vintage — fly a standard approach and be ready for firm control inputs.", allowedAircraft: ["U16"] },
        { imgId: 13, missionType: 13, payload: "Commemorative SAR Demo", instruction: "You are flying a commemorative SAR route for the crews who operated these flying boats. Keep your eyes outside, stay low where you can and fly smooth sweeping turns.", allowedAircraft: ["U16"] }
    ],
        commercial: [
        { imgId: 14, payload: "flying {team} to their next fixture", instruction: "You have {team} on board with the coaching staff and medical kit. Keep the climb and descent gentle so nobody is bouncing around before kick-off.", weight: 3 },
        { imgId: 15, payload: "flying a holiday charter group", instruction: "You have a cabin full of holiday passengers who have finally got time off work. Give them a steady ride and let the holiday start in the air." },
        { imgId: 16, payload: "recovering passengers after widespread weather groundings", instruction: "Yesterday's storms grounded half the network. You have a full cabin of tired passengers who just need to get where they were meant to be.", weight: 3 },
        { imgId: 17, payload: "transporting travellers between hubs", instruction: "You are on a scheduled hub link today. Big metal, big airports — fly the filed route and settle her early on the approach." },
        { imgId: 18, payload: "transporting tourists to their destination", instruction: "You have a packed cabin of tourists in holiday mood and a schedule that does not forgive. Hit the block times or you will hear about it at the gate." },
        { imgId: 19, payload: "ferrying professionals to a major tech convention", instruction: "You have a cabin of tech professionals with laptops open from pushback. Keep it smooth in the cruise so the passengers can work instead of gripping the armrests.", weight: 3 },
        { imgId: 20, payload: "operating a high-capacity holiday route", instruction: "You are on a peak-season holiday route and the sky is busy. Listen for holds, watch the fuel and do not get caught short if ATC stacks you up." },
        { imgId: 21, payload: "recovering a diverted flight after a regional system outage", instruction: "The passengers have been stuck for hours after the diversion. Climb clean, bring her down continuous if you can and get the cabin on the ground without drama." },
        { imgId: 22, payload: "ferrying a corporate group to an annual summit", instruction: "You have a corporate group in the back after a long week. Skip the chatty PAs and fly a quiet, smooth sector to the summit." },
        { imgId: 23, payload: "operating the airline's most popular route", instruction: "You are on the airline's flagship route today. Everyone knows this run — fly it clean and expect a quick turn once you are on stand." },
        { imgId: 24, payload: "operating a scheduled commercial sector", instruction: "The clock is against you on this scheduled sector. Ask for priority on the approach if it is on offer and get the passengers offloaded as soon as you block in." },
        { imgId: 25, payload: "operating a standard commercial sector", instruction: "You have ordinary line flying today. Fly it by the book and keep the schedule honest." },
        { imgId: 26, payload: "shuttling morning business travelers from hub to hub", instruction: "You are shuttling morning business passengers between hubs. ATC will want you in the flow with the jets — hold the speed they ask for and get on the brakes once you are down." },
        { imgId: 27, payload: "transporting university students to a massive event", instruction: "You have a full cabin of university students heading to a massive event. The cabin is loud and bags are stuffed in the hold — leave the belt sign on if it gets rowdy back there." },
        { imgId: 28, payload: "transporting a full symphony orchestra and their instruments", instruction: "You have a touring symphony orchestra on board and a hold full of instrument cases that do not bounce well. Climb easy and ride out the bumps if you can." },
        { imgId: 29, payload: "flying a group of exchange students to their host country", instruction: "You have a cabin of excited exchange students on the way to host families. Nothing fancy needed — just a safe, steady flight and an on-time arrival.", weight: 3 },
        { imgId: 30, payload: "transporting company personnel to a seminar", instruction: "You are moving company personnel to a big integration seminar after the merger. Full cabin, straightforward sector — get the workforce there on time." },
        { imgId: 31, payload: "flying fans to a major championship final", instruction: "You have nothing but football supporters heading to the championship final. The cabin is loud, happy and already celebrating in row twelve." },
        { imgId: 32, payload: "transporting retirees to warmer climates for the winter", instruction: "You have seasonal sun-seekers filling every seat. Soft rotation, soft landing and no heroics in between." }
    ],
    'commercial-regional': [
        { imgId: 33, payload: "flying a short regional commuter hop", instruction: "You have a short regional hop and a quick turn waiting on the ground. Keep the block tight and fly it like the turboprop or regional jet it is." },
        { imgId: 34, payload: "working a string of short sectors with fast turns", instruction: "You are working a string of short sectors today. If your airframe has Hotel Mode or something like it, use it on the ground so the cabin stays live without chasing a GPU." },
        { imgId: 35, payload: "keeping a rural town linked into the network", instruction: "This run matters to the towns it serves. Stick to the schedule — plenty of passengers are counting on a connection at the other end." },
        { imgId: 36, payload: "flying a quiet late-evening commuter sector", instruction: "You have a quiet late-evening sector tonight. The sky is thin — climb efficiently and do not burn fuel you do not need." },
        { imgId: 37, payload: "recovering passengers after widespread weather groundings", instruction: "You have a full cabin of tired short-haul passengers who just want this one sector done after yesterday's groundings." },
        { imgId: 38, payload: "taking holidaymakers to their destination", instruction: "You have a regional leisure run with every seat taken. Hit the block times — the passengers are ready for the holiday the moment you open the doors." },
        { imgId: 39, payload: "recovering a diverted flight after a regional system outage", instruction: "The regional system has been down for hours. You have a full cabin of tired passengers who need to get home — fly a clean descent and make the sector count." },
        { imgId: 40, payload: "ferrying a corporate group to an annual summit", instruction: "You have a corporate group in the back with a clock running on the ground. Quiet PAs, smooth cruise and no drama on the way to the summit." },
        { imgId: 41, payload: "flying the airline's busiest regional route", instruction: "You are on the busiest regional feeder in the network. Fly it clean and expect a fast turn at the gate." },
        { imgId: 42, payload: "flying a scheduled hub feeder sector", instruction: "You have ordinary hub feeder work today. Ask for a better sequence if ATC will give it, then get the passengers off the jet as soon as you block in." },
        { imgId: 43, payload: "flying a group of exchange students to their host country", instruction: "You have excited exchange students on the way to host families. Keep it smooth, keep it on time and nothing fancy." },
        { imgId: 44, payload: "moving company staff to a seminar", instruction: "You are moving company staff to a seminar after the office shuffle. Full cabin, short sector — keep the schedule tight." }
    ],
	executive: [
        { imgId: 45, payload: "flying {name} on a private schedule", instruction: "{name} wants the cabin quiet the whole way. Smooth climb, smooth descent and keep the ride soft.", weight: 15, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED, allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 46, payload: "taking {athlete} to an upcoming fixture", instruction: "You have {athlete} on board and the fixture is coming up fast. Keep chatter off the PA and fly it smooth so {athlete} can rest before the game.", weight: 15, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 47, payload: "flying executives to a negotiation", instruction: "You have executives working the deal in the back. Soft ride, few announcements and no drama on the way to the negotiation.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 48, payload: "flying a board to an offsite", instruction: "The cabin is a flying office today. Dodge the bumps so the board can keep working on the way to the offsite.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 49, payload: "flying state representatives", instruction: "You have state representatives on the manifest. Fly it by the book and keep the whole sector professional.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 50, payload: "flying a {vip_type} to a high-level conference", instruction: "You have a {vip_type} on board heading to a high-level conference. Easy on the controls and keep the cabin comfortable.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 51, payload: "shuttling executives to a regional facility", instruction: "You have executives with a tight ground schedule waiting at the facility. Hit the block times and get the cabin there on time.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 52, payload: "flying a premium share owner", instruction: "You have a premium share owner on board who is used to the best. Make the whole trip look effortless.", allowedClasses: ["BIZ JET", "TURBO", "HELI"], weight: 3 },
        { imgId: 53, payload: "flying prospective investors", instruction: "You have prospective investors in the back being sold the company from the cabin. Keep the flight butter-smooth.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 54, payload: "moving a secure witness", instruction: "You have a secure witness on board — point to point, no fuss, no attention. Park at the FBO and stay away from the main terminal.", allowedAircraft: ["C208", "STAR", "M600", "TBM8", "B60T", "BE20", "PC12", "H145", "H14M"], allowedClasses: ["BIZ JET"], weight: 3 },
        { imgId: 55, payload: "ferrying a Renaissance masterpiece to a private buyer", instruction: "You have a Renaissance masterpiece on board worth more than the jet. Hold cabin temp and humidity steady and stay clear of convective weather.", weight: 1, allowedClasses: ["BIZ JET", "TURBO", "HELI"], excludedAircraft: SMALL_GA_TRAINERS },
        { imgId: 56, payload: "rushing legal executives to an industrial incident", instruction: "A PR mess is brewing on site and the legal team in the back is planning as you fly. Shorten the route wherever you can safely.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 57, payload: "flying a tech mogul's purebred cat", instruction: "You have a prize cat coming home from a luxury pet retreat. Gourmet tuna, velvet cushions, shallow banks — treat this feline like royalty.", weight: 1, allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 58, payload: "chartering a high-profile music icon", instruction: "{musician} wants to go shopping. Keep the pressurization soft and the banks shallow so the champagne stays in the glass.", weight: 12, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 59, payload: "flying an owner to a holiday retreat", instruction: "You have an owner in the back with golf clubs and weekend bags. Enjoy the view on the scenic approach and keep the landing soft.", allowedClasses: ["BIZ JET"] },
        { imgId: 60, payload: "flying a short-hop business commute", instruction: "You are skipping the airline queues today. Ask for directs where ATC will give them and shorten the block time where you can.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 61, payload: "flying {musician} to their next stadium gig", instruction: "{musician} and the management team need sleep before the show. Climb above the weather, dodge the bumps and keep cabin pressure steady.", weight: 12, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 62, payload: "flying {name} to meet a spiritual guru", instruction: "You are flying {name} to meet a spiritual guru and the press is watching this tail number. Park somewhere quiet on arrival and keep {name} off open channels.", weight: 15, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED, excludedAircraft: SMALL_GA_TRAINERS },
        { imgId: 63, payload: "flying {athlete} to a championship fixture", instruction: "{athlete} needs to arrive rested and on time for the championship fixture. Ask for priority if it is on offer and keep the ride smooth.", weight: 15, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 64, payload: "flying {name} to a film premiere", instruction: "You are flying {name} to a film premiere and the cameras will be everywhere on the ground. Quiet on frequency, clean approach and a quick turn at the FBO.", weight: 15, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 65, payload: "flying {team} executives to an away fixture", instruction: "{team} executives are on board for an away fixture and the media are watching. Smooth profile and hit the scheduled block.", weight: 12, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 66, payload: "rushing a surgical team to a regional hospital", instruction: "You have a surgical team on board and the hospital is waiting. Use the speed you have got, ask ATC for priority and do not waste a minute.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 67, payload: "flying a VIP to an exclusive private gala", instruction: "You have a VIP charter with the bar stocked for comfort. Butter-smooth landing so the passenger arrives in a good mood.", weight: 15, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 68, payload: "rushing a tech CEO to a hostile board meeting", instruction: "The stock is in freefall and the CEO needs to be on the ground now. Expedite everything and do not keep the cabin waiting.", allowedClasses: ["BIZ JET", "TURBO", "HELI"], excludedAircraft: ["UH1", "H14M", "H65M"] },
    ],
	medical: [
        { imgId: 69, payload: "airlifting a patient", instruction: "You have a patient on board who is stable, but rough air will not help. Watch the radar and keep the ride smooth all the way in." },
        { imgId: 70, payload: "transporting tissue for surgery", instruction: "Lifeguard priority — surgical tissue is on board. Ask ATC for priority on the way in. Helicopters go to the hospital; everyone else meets the ground crew on arrival." },
        { imgId: 71, payload: "airlifting a patient from a rural strip", instruction: "You may be heading into an uncontrolled field for this patient pickup. Check the runway before you commit to the approach." }
    ],
	lightFreight: [
        { imgId: 72, payload: "moving classified diplomatic files", instruction: "You have classified diplomatic files on board and chain of custody is everything. Straight point to point and no unscheduled stops." },
        { imgId: 73, payload: "delivering prototype processing units", instruction: "You have prototype hardware in the hold that is sensitive to static and temperature. Check the environmental controls before you taxi." },
        { imgId: 74, payload: "moving a protected animal species", instruction: "You have live cargo in the back. Shallow banks and easy on the thrust." },
        { imgId: 75, payload: "delivering fragile conservation saplings", instruction: "You have living plants on board with pressurization limits. Watch your descent rate on the way in." },
        { imgId: 76, payload: "flying primary digital master drives", instruction: "You have unedited production footage in the hold and the edit suite is waiting. Ask for a shorter route if ATC will give it." },
        { imgId: 77, payload: "relocating fragile historical manuscripts", instruction: "You have climate-controlled manuscript cases on board. Have ground handling ready the moment you block in." },
        { imgId: 78, payload: "rushing a critical AOG component", instruction: "Another aircraft is stuck waiting on this part. Shorten the route and do not linger on approach." },
        { imgId: 79, payload: "expediting priority medical freight", instruction: "You have temp-controlled medical cargo for a regional hospital. Ask ATC for priority and keep pressurization steady." },
        { imgId: 80, payload: "transporting {med_cargo}", instruction: "You have {med_cargo} in the hold. Keep cabin temperature locked in and avoid fast climbs or descents that spike the pressure." },
        { imgId: 81, payload: "expediting {med_cargo}", instruction: "A regional clinic needs this {med_cargo} for a procedure today. Keep the block as short as you can safely manage." },
        { imgId: 82, payload: "hauling farm produce from a rural strip", instruction: "You have fresh produce loaded straight from the field. Get airborne while it is still cold and dry." },
        { imgId: 83, payload: "moving regional express packages overnight", instruction: "You are on a night freight run. Hit your slots so the network does not stall.", excludedAircraft: MAINLINE_JET_FREIGHTERS },
        { imgId: 84, payload: "delivering regional post parcels", instruction: "You have an old-school mail run tonight. Weight is tight at every stop — do not hang about, you have more drops before sunset.", allowedAircraft: ["C20F", "C208", "KODF", "PC1F"] },
        { imgId: 85, payload: "delivering essential supplies to customers", instruction: "You have supplies and mail in the hold. Recheck density altitude before you commit to the departure." },
        { imgId: 86, payload: "delivering regional supplies", instruction: "You have a regional supply run today. Work the landing numbers for your arrival weight and use reverse if the runway is short.", excludedAircraft: ["B72F"] },
 		{ imgId: 87, payload: "shuttling regional lab samples and {med_cargo}", instruction: "You are running {med_cargo} direct and skipping the hubs. Small load, big stakes — stick to the planned block." },
        { imgId: 88, payload: "distributing the morning broadsheets", instruction: "It is 4 AM, the coffee is weak and the hold is full of today's news. Get the ink to the distributors before breakfast." },
        { imgId: 89, payload: "rushing iced premium seafood to inland markets", instruction: "The ice is already melting on this catch. Get it to the restaurants before the dinner rush and keep the ECS freezing cold." },
        { imgId: 90, payload: "relocating the airframe to a certified avionics shop", instruction: "The owner says the GPS is acting up. Fly it carefully and keep your eyes outside." },
        { imgId: 91, payload: "rushing a rare component to a stranded client", instruction: "A wealthy client's vintage car is stuck waiting on this part. Push cruise where you can, but keep the gauges in the green." },
        { imgId: 92, payload: "ferrying critical machinery parts to a regional facility", instruction: "Harvest season and an essential machine is down on the field. Get these parts there as fast as you safely can." },
        { imgId: 93, payload: "delivering a recently purchased airframe", instruction: "The broker just handed over the keys. Take her home, watch the temps — she has not flown much this season." },
        { imgId: 94, payload: "connecting rural farm strips with mail and supplies", instruction: "You have a classic grass-strip hop before sunset. Weight checked at every stop — crisp patterns and soft landings." },
        { imgId: 95, payload: "delivering supplies to a community", instruction: "You have food, fuel and mail for a place with no road in. Check your landing performance for the short strip.", allowedAircraft: ["C20F", "C208", "KODF", "PC1F"] }
    ],
    regionalFreight: [
        { imgId: 96, payload: "moving regional express packages overnight", instruction: "You are on a regional night express run. Hit the slots so the network does not stall.", excludedAircraft: MAINLINE_JET_FREIGHTERS, preferredAircraft: REGIONAL_JET_FREIGHTERS },
        { imgId: 97, payload: "moving priority overnight parcels", instruction: "The sort facility is on the clock. Ask for directs if there were delays getting in the air.", preferredAircraft: REGIONAL_JET_FREIGHTERS },
        { imgId: 98, payload: "flying an overnight regional freight sector", instruction: "You have a red-eye clearing the regional hubs. Stick to your ATC slots and keep the descent clean while the sky is quiet.", preferredAircraft: REGIONAL_JET_FREIGHTERS },
        { imgId: 99, payload: "expediting priority medical freight", instruction: "You have temp-controlled medical cargo for a regional hospital and you are the quickest link. Ask ATC for priority." },
        { imgId: 100, payload: "shuttling regional lab samples and {med_cargo}", instruction: "You are running {med_cargo} direct and skipping the hubs. The lab teams are waiting — do not waste time on the ground." },
        { imgId: 101, payload: "ferrying critical machinery parts to a regional facility", instruction: "Harvest season and an essential machine is down. Push cruise where you can and get these parts to the field." },
        { imgId: 102, payload: "delivering regional supplies", instruction: "You have a supply run for regional businesses. Work the landing numbers for your arrival weight and use reverse if the runway is short.", excludedAircraft: ["B72F"], preferredAircraft: REGIONAL_JET_FREIGHTERS },
        { imgId: 103, payload: "flying a late-evening regional freight sector", instruction: "You have a late red-eye on a quiet regional network. Traffic is thin — fly efficiently and keep the chain moving through the night.", preferredAircraft: REGIONAL_JET_FREIGHTERS }
    ],
	heavyFreight: [
        { imgId: 104, payload: "delivering palletized nutrition and water packs", instruction: "Local supply chains are broken and relief pallets are on board. Ask for a direct where you can and get the cargo in." },
        { imgId: 105, payload: "delivering retail warehouse garment supplies", instruction: "You have boxed clothing for the warehouses in the hold. Keep it clean and dry all the way in.", excludedAircraft: MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT },
        { imgId: 106, payload: "moving authenticated historical artifacts", instruction: "You have fragile museum pieces on board. Descend with care, go easy on the brakes and no loops today.", weight: 3, excludedAircraft: MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT },
        { imgId: 107, payload: "moving {cargo_type}", instruction: "Engineers are waiting on this {cargo_type}. Stick to the block times and get it on the ground cleanly.", excludedAircraft: ["DC6A"].concat(MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT) },
        { imgId: 108, payload: "delivering luxury vehicles and parts", instruction: "You have high-value, dense freight on the main deck. Make sure the loadmaster has checked every strap before you close the door.", excludedAircraft: ["B461_MIL", "B462_MIL", "DC6A"].concat(MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT) },
        { imgId: 109, payload: "loading a high-value luxury sports car", instruction: "You have a bespoke supercar on board for delivery. Easy on the controls and confirm the straps are secure before you close up.", weight: 3, excludedAircraft: ["B461_MIL", "B462_MIL", "DC6A"].concat(MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT) },
        { imgId: 110, payload: "ferrying {cargo_type} and heavy oilfield equipment", instruction: "You have {cargo_type} and heavy oilfield kit bolted to the floor rails. You will be slower today — watch the burn and stay ahead of the power curve on final." },
        { imgId: 111, payload: "returning a decommissioned avionics bay", instruction: "You have regular industrial freight on the deck. Check the tie-downs before you roll." },
        { imgId: 112, payload: "transporting premium edible goods for wholesale", instruction: "You have premium perishables in the hold. Keep the temperature steady so nothing spoils — you do want to get paid, don't you?", excludedAircraft: MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT },
        { imgId: 113, payload: "transporting bulk commercial perishables", instruction: "You have heavy density cargo in the hold. Watch your V-speeds on the takeoff roll.", excludedAircraft: MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT },
        { imgId: 114, payload: "moving priority overnight parcels", instruction: "The sort facility is on the clock. Ask for directs if there were delays getting in the air.", excludedAircraft: MIL_AIRLIFTER_EXCLUDED_OVERNIGHT_PARCELS.concat(REGIONAL_JET_FREIGHTERS) },
        { imgId: 115, payload: "transporting heavy secure bullion", instruction: "You have a central bank transfer on board with serious security on the ramp. The ground team will handle the load on and off.", weight: 3 },
        { imgId: 116, payload: "moving an oversized, max-payload cargo manifest", instruction: "You are right at MTOW today. Long roll, lazy climb — double-check the V-speeds before you commit.", excludedAircraft: ["DC6A"] },
        { imgId: 117, payload: "flying an overnight route", instruction: "You have a red-eye clearing the big sorting hubs. Hit your ATC slots and manage that heavy descent while the sky is quiet.", preferredAircraft: REGIONAL_JET_FREIGHTERS, excludedAircraft: MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT },
        { imgId: 118, payload: "moving an absolute mountain of impulse buys", instruction: "The sort facility is backed up and the hold is stuffed to the roof. Expect a slow rotate and a step-climb if the air is warm tonight.", excludedAircraft: MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT },
        { imgId: 119, payload: "transporting Formula racing chassis and paddock gear", instruction: "You have high-value, time-critical and fragile Formula gear on board. Keep the bumps down — those front wings cost more than a house.", weight: 3, excludedAircraft: ["DC6A", "B461_MIL", "B462_MIL"].concat(MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT) },
        { imgId: 120, payload: "loading heavy industrial machinery", instruction: "The loadmaster is still chaining oversized plant kit to the main deck. Confirm tie-downs and floor limits before you call for push.", excludedAircraft: ["DC6A"] },
        { imgId: 121, payload: "loading a heavy industrial generator", instruction: "Ground crew are locking down an oversized generator on the deck. Check floor limits, chains and CG before pushback.", excludedAircraft: ["DC6A"] },
        { imgId: 122, payload: "transporting a replacement engine turbine module", instruction: "You have a fragile fan module on board for an AOG recovery. Keep the ride smooth and the hold temp steady." },
        { imgId: 123, payload: "transporting server racks and data-centre hardware", instruction: "You have server racks and data-centre hardware in the hold. Fly smooth, keep cabin temp in spec and do not ask what runs on these machines." }
    ],
    surveyServices: [
        { imgId: 124, payload: "distributing localized civic awareness materials", instruction: "You are flying the assigned grid so the civic leaflet drop covers the sector evenly. Stay on the planned track." },
        { imgId: 125, payload: "surveying local power and pipeline grids", instruction: "You are surveying the power and pipeline grid today. Stay within the inspection corridor and keep a sterile cockpit while you are on the line." },
        { imgId: 126, payload: "inspecting crop yields", instruction: "You are low and slow over the fields today. Watch for unmarked power lines and keep the track steady for the survey team." },
        { imgId: 127, payload: "mapping a municipal expansion zone", instruction: "You are mapping a municipal expansion zone. Hold a steady track along the route so the survey team gets clean readings." },
        { imgId: 128, payload: "mapping subsurface anomalies", instruction: "You are mapping subsurface anomalies today. Hold constant airspeed and altitude — the magnetometer hates wandering." },
        { imgId: 129, payload: "flying insurance assessment teams", instruction: "A storm tore through here yesterday. Hold the profile over the damage so the insurance assessors can scan from above." },
        { imgId: 130, payload: "flying LIDAR equipment over suspected ancient ruins", instruction: "Researchers want LIDAR passes over suspected ruins below. Hold altitude and track tight across the grid so the survey team gets clean coverage." },
        { imgId: 131, payload: "flying a photographer for a high-end property portfolio", instruction: "You have a photographer on board who needs clean, stable orbits over a few waypoints. Work with the photographer and keep the airframe smooth.", excludedAircraft: ["U16"] },
        { imgId: 132, payload: "flying researchers over a {sci_fi}", instruction: "Researchers want you over a {sci_fi} on this route. Map it from above and try to ignore the weird static chewing through the radios.", weight: 3 },
        { imgId: 133, payload: "assisting authorities in a visual search for a missing vehicle", instruction: "You are assisting a visual search for a missing vehicle. Fly low over the last known coordinates and keep your eyes outside for anything that looks like a signal.", weight: 3, excludedAircraft: ["BE60", "STAR"] },
    ],
    lightPax: [
        { imgId: 134, payload: "moving industrial staff between sites", instruction: "You have an ordinary staff shuttle today. Nothing fancy — get the passengers there on time." },
        { imgId: 135, payload: "conducting a standardization flight", instruction: "You are conducting a standardization flight in the local pattern. Standard maneuvers and clean radio work.", weight: 3 },
        { imgId: 136, payload: "shuttling an independent engineering consultant", instruction: "You have an engineering consultant working paperwork in the back. Find smooth air and keep the inputs gentle." },
        { imgId: 137, payload: "keeping a community linked by light aircraft", instruction: "This town relies on your connection. Stick to the schedule — plenty of passengers have onward flights at the hub." },
        { imgId: 138, payload: "flying {name} on a private schedule", instruction: "{name} wants quiet and discretion on this run. Smooth climb, smooth descent and keep the ride soft.", weight: 12, allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 139, payload: "flying {name} to meet a spiritual guru", instruction: "You are flying {name} to meet a spiritual guru and the press is watching this flight. Park away from the main building and keep {name} off open channels.", weight: 12, excludedAircraft: SMALL_GA_TRAINERS, allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 140, payload: "flying a romantic scenic twilight flight", instruction: "You have a romantic twilight scenic on the books tonight. Smooth RPM, shallow banks and a gentle profile — do not spoil the moment.", weight: 1 },
        { imgId: 141, payload: "rushing a stranded businessman to a regional hub", instruction: "You have a stranded businessman who missed the airline connection and grabbed your last seat. Can you save the day and get him to the hub on time?", weight: 2 },
        { imgId: 142, payload: "bringing passengers home to their families", instruction: "You are the only link between these towns today. Plan the fuel, watch the approach winds and butter that landing." },
        { imgId: 143, payload: "flying a honeymooning couple to a remote retreat", instruction: "You have a honeymooning couple on a chartered getaway. Gentle turns, smooth air and a soft landing — match the holiday mood.", weight: 1 },
        { imgId: 144, payload: "flying a regional medical examiner to an incident site", instruction: "You have a regional medical examiner on a time-sensitive call-out. Get to the incident site as fast as you safely can and check the runway before you commit.", weight: 3 },
        { imgId: 145, payload: "delivering urgent freight to a private airstrip", instruction: "A rural estate needs materials now and it is a short strip. Watch the crosswind on final and get the freight down cleanly." },
        { imgId: 146, payload: "repositioning an aircraft for its new owner", instruction: "The deal is done and the keys are handed over. Ferry her to the new home base, watch the temps — unfamiliar airframe today." }
    ],
    highAltServices: [
        { imgId: 147, payload: "gathering specific meteorological data", instruction: "You are gathering meteorological data for the science team. Fly the altitudes and headings they ask for — the readings only count if you nail the profile." },
        { imgId: 148, payload: "flying atmospheric researchers to a developing system", instruction: "You have atmospheric researchers who need to drop sensors ahead of a major pressure shift. Get close enough to observe, but stay clear of the convective cells." }
    ],
    vintageOps: [
        { imgId: 149, payload: "flying a historic airshow demonstration", instruction: "You are flying a historic airshow demonstration today. Static display on the ground, then a short aerial routine — check the fluids before you roll.", allowedClasses: ["WARBIRD", "JET"], excludedAircraft: ["DC6A"], weight: 3 },
        { imgId: 150, payload: "positioning for a closed-course handicap race", instruction: "You are positioning for a closed-course handicap race. Visual transit to the staging field and keep the airframe clean and trimmed.", excludedAircraft: ["U16", "DC6A", "DC6B", "V10", "P38"] },
        { imgId: 151, payload: "ferrying a vintage airframe to an aviation museum", instruction: "You are ferrying a vintage airframe to the museum. Treat her gently, stay well inside the structural limits — she is old and the museum wants her in one piece." },
        { imgId: 152, payload: "acting as a chase plane for a historic squadron", instruction: "You are chase plane for a historic squadron today. Hold your spacing, stay aware and watch the temps — formation power settings can run hot.", allowedClasses: ["GA"] },
        { imgId: 153, payload: "flying a commemorative low-level transit", instruction: "You are flying a commemorative low-level transit. Hit time-on-target over the memorial clean and keep it respectful." },
        { imgId: 154, payload: "keeping current in a historic airframe", instruction: "You are keeping current in a historic airframe. Local pattern work so you and the aircraft stay approved for the next public display." },
        { imgId: 155, payload: "delivering a newly restored airframe to a preservation trust", instruction: "You are delivering a newly restored airframe to the preservation trust. She is irreplaceable — watch the gauges, dodge convective weather and deliver her clean to the museum ramp." },
        { imgId: 156, payload: "ferrying to a regional aviation festival", instruction: "You need to be on the staging grounds before sunset. Cruise power conservative to spare the engine — expect a crowd watching your arrival." },
        { imgId: 157, payload: "flying a chartered remembrance flight", instruction: "You are flying a chartered remembrance flight in memory of those who flew this airframe before you. Keep the maneuvers gentle and the fluids in the green.", weight: 3 }
    ],
	// DC-6A freight exclusive
    vintageProplinerFreight: [
        { imgId: 158, payload: "hauling oversized vintage freight", instruction: "You have a classic load for a classic bird. Keep the RPMs synced, mind the cowl flaps and plan your descent early — no speedbrakes on this one." },
        { imgId: 159, payload: "flying live agricultural freight", instruction: "The hold smells terrible, but the payout is good. Easy on the bank angles and grease the landing." },
        { imgId: 160, payload: "moving heavy goods in a vintage airframe", instruction: "You are moving heavy goods in a vintage airframe today. Watch the engine temps, work the flight engineer panel and expect the controls to feel a bit slow.", allowedAircraft: ["DC6A"] },
        { imgId: 161, payload: "loading palletized commercial freight", instruction: "The warehouse teams are still building the pallets. Hit your departure slot or the whole sort window slips.", preferredAircraft: ["DC6A"] }
    ],
	// DC-6B PAX Exclusive
    vintageAirliner: [
        { imgId: 162, payload: "flying a premium overnight cross-country", instruction: "You have a premium overnight cross-country with half the cabin asleep. Keep the pitch smooth and the step-climb easy so the passengers stay that way.", allowedAircraft: ["DC6B"], excludedAircraft: ["DC6A"] },
        { imgId: 163, payload: "flying holidaymakers across the country", instruction: "You have holidaymakers across the country today. Watch the cylinder head temps on the ground and get the cowl flaps sorted early before you pick through any local weather.", allowedAircraft: ["DC6B"], excludedAircraft: ["DC6A"] },
        { imgId: 164, payload: "flying a full load of {industry} executives and engineers to the extraction sites", instruction: "You have a full load of {industry} executives and engineers for the extraction sites. Have the flight engineer keep cross-feeds tidy so the centre of gravity stays balanced.", allowedAircraft: ["DC6B"], excludedAircraft: ["DC6A"] },
        { imgId: 165, payload: "flying sports fans to the match", instruction: "You have sports fans heading to the match. Check carb heat and the de-icing boots before you enter the terminal area.", allowedAircraft: ["DC6B"], excludedAircraft: ["DC6A"] },
        { imgId: 166, payload: "flying an iconic passenger shuttle", instruction: "You are on an iconic passenger shuttle today. Expect a lazy climb off the runway — mind the power recovery and do not thrash the engines.", allowedAircraft: ["DC6B"], excludedAircraft: ["DC6A"] }
    ],
    'helicopterOps-CIV': [
        { imgId: 167, payload: "flying a local scenic hop", instruction: "You have passengers on a local scenic hop today. Take them around the landmarks on a visual pattern, then set down at the destination and keep clear of the GA traffic." },
        { imgId: 168, payload: "holding steady for a survey photographer", instruction: "You are holding steady for a survey photographer. Work with the photographer and give clean orbits over the waypoints — smooth is everything." },
        { imgId: 169, payload: "watching the local transit corridors", instruction: "You are watching the local transit corridors from above. Hold over the big interchanges so the spotter can call traffic conditions — easy turns, predictable track." },
        { imgId: 170, payload: "flying a short on-demand charter", instruction: "You have a client who wants to skip the gridlock. Direct routing if you can get it and do not hang about." },
        { imgId: 171, payload: "extracting a trauma victim from a major roadway", instruction: "First responders have a landing zone ready on the roadway. Get in, get the patient aboard and go — the clock is running." },
        { imgId: 172, payload: "searching for a stranded group of travellers", instruction: "You are searching for a stranded group of travellers. Work patterns over the last known coordinates and be ready to hoist if you cannot put down." },
        { imgId: 173, payload: "providing aerial overwatch", instruction: "You are providing aerial overwatch for ground units. Talk to the ground team, hold a safe height over the target area and stay predictable." },
        { imgId: 174, payload: "mapping a new property development", instruction: "You are mapping a new property development. Fly precise tracks across the survey grid so the cameras get clean, overlapping coverage." },
        { imgId: 175, payload: "positioning industrial equipment", instruction: "You are positioning industrial equipment with a precision hover. Watch torque and engine limits the whole time you are hanging there." },
        { imgId: 176, payload: "locating tagged animal populations", instruction: "You are locating tagged animal populations for the biologists. Keep visual contact while the telemetry is logged and do not spook the wildlife if you can help it." },
        { imgId: 177, payload: "shuttling an executive from the airport", instruction: "You have an executive hop from the FBO to the helipad. Smooth transition, soft set-down and no drama." },
        { imgId: 178, payload: "covering a civic event live", instruction: "You are covering a civic event live from the air. Set up a loiter clear of other traffic and keep your movements predictable for the camera operator." },
        { imgId: 179, payload: "capturing dynamic tracking shots", instruction: "You are capturing dynamic tracking shots today. Work with the ground director, match the subject's pace and keep the follow smooth with no sudden inputs." },
        { imgId: 180, payload: "moving heavy pipe segments into rugged terrain", instruction: "You have external load work moving heavy pipe segments into rugged terrain. Watch torque and rotor RPM while you ease the segments into place.", minCargo: 201 },
        { imgId: 181, payload: "cleaning high-tension wire infrastructure", instruction: "You are cleaning high-tension lines today. Fly low and slow so the boom operator can hit the insulators. Mind the wind — you do not want to drift into the wires." },
        { imgId: 182, payload: "transporting highly sensitive legal tenders", instruction: "You have highly sensitive legal tenders on board and the case is handcuffed to the courier. Fly straight and be ready for an engine-running offload the moment you arrive." },
        { imgId: 183, payload: "airlifting an unidentifiable metallic pillar", instruction: "Hikers found a smooth, heavy metal pillar in a slot canyon. Ground crews say the air goes cold near it and your compass will not settle.", minCargo: 201, weight: 3 },
    ],
	// MILITARY
	'heavyFreight-MIL': [
        { imgId: 184, payload: "moving dense tactical vehicle components", instruction: "You have a heavy tactical load today. Double-check the CG on the loadsheet before you start the engines." },
        { imgId: 185, payload: "relocating modular defense components", instruction: "The depot needs this kit for assembly the moment you land. Stick to the filed plan and hit the block." },
        { imgId: 186, payload: "moving sensitive industrial hardware", instruction: "You have sealed manifests and no questions on this run. Head straight for the remote ramp when you arrive." },
        { imgId: 187, payload: "ferrying urgent technical spares to a regional depot", instruction: "You have a priority load on board. Get it there on time or the maintenance schedule slips." },
        { imgId: 188, payload: "transporting AOG parts for a fleet-wide inspection", instruction: "Maintenance are standing by for this hardware. Do not waste a minute on the way in." },
        { imgId: 189, payload: "loading tactical cargo pallets", instruction: "You have palletized military stores going on the main deck. Check tie-down tension and CG before you start engines.", allowedAircraft: ["C160"] },
        { imgId: 190, payload: "delivering refugee relief supply pallets", instruction: "You have humanitarian pallets bound for a forward distribution point. Keep the schedule and make sure the offload teams are ready when you land.", allowedAircraft: ["C160", "A400"] }
    ],
    'helicopterOps-MIL': [
        { imgId: 191, payload: "deploying a specialized ground team", instruction: "You are deploying a specialized ground team into the LZ. Use the terrain on the way in, stabilize the hover and get the team out clean.", heliOps: true },
        { imgId: 192, payload: "conducting a perimeter survey", instruction: "We have reports of suspicious movement along the vector. Hold corridor track, log contacts and watch loiter fuel. Do not engage.", heliOps: true },
        { imgId: 193, payload: "flying visiting dignitaries around the installation", instruction: "You have visiting dignitaries on board who want clear photos of the base from a safe standoff. Soft ride and predictable banks.", staffShuttle: true },
        { imgId: 194, payload: "conducting a local SAR training sortie", instruction: "You are outbound to the training grid for low-altitude hover work. Keep your eyes peeled for the training beacons.", heliOps: true },
        { imgId: 195, payload: "delivering essential provisions to an observation post", instruction: "You have field rations and spare radio batteries in the back. Ease into the LZ and watch for wind shear off the terrain.", heliOps: true },
        { imgId: 196, payload: "transporting regional commanders to a joint briefing", instruction: "You have regional commanders on board for a joint briefing. Comfortable transit, direct routing and no sightseeing — security wants you there with no detours.", staffShuttle: true },
        { imgId: 183, payload: "airlifting an unidentifiable metallic pillar", instruction: "Hikers found a smooth, heavy metal pillar in a slot canyon. Ground crews say the air goes cold near it and your compass will not settle.", minCargo: 201, weight: 3, heliOps: true }
    ],
    'militaryTransit-MIL': [
        { imgId: 197, payload: "transferring encrypted telemetry hardware", instruction: "You have secure flight data recorders from a defense contractor on board. Standard OPSEC — keep it quiet and stick to the plan." },
        { imgId: 198, payload: "moving unmarked secure containers", instruction: "You have unmarked secure containers on the flight plan. Talk normally on the radio, but go straight to destination." },
        { imgId: 199, payload: "relocating contracted defense personnel", instruction: "You have a standard military charter with contracted defense personnel on board. Hit the schedule and fly it like any heavy jet sector.", excludedAircraft: ["VULC"], requiresPax: true },
        { imgId: 200, payload: "repositioning to a strategic staging airfield", instruction: "You are on a peacetime repositioning to a strategic staging airfield. Sterile cockpit and work with military ATC for your arrival window." },
        { imgId: 201, payload: "executing a peacetime navigation exercise", instruction: "You are executing a peacetime navigation exercise. Nail the fuel plan and the waypoint timings — fly the exercise by the numbers." },
        { imgId: 202, payload: "relocating staff personnel under tactical escort", instruction: "You have a low-profile transit with staff personnel under escort. Direct routing, assigned levels and no deviations from the flightplan.", excludedAircraft: ["VULC"], requiresPax: true },
        { imgId: 203, payload: "delivering priority diplomatic communications", instruction: "You have priority diplomatic communications on board. Maintain chain of custody and do not leave the filed flightpath." },
        { imgId: 204, payload: "transferring cryogenic xenobiological tissue samples", instruction: "Captain, this flight officially does not exist. Ignore any knocking from the hold and do not log the sector.", weight: 1 },
        { imgId: 205, payload: "providing high-speed search and rescue support", instruction: "You are providing high-speed SAR support along the route. Scan for beacons or visual distress, pass coordinates to the extraction teams and hold your search profile." },
        { imgId: 206, payload: "patrolling the designated vector for surface anomalies", instruction: "You are patrolling the designated vector for surface anomalies. Keep eyes on the surface and call any unregistered traffic up to sector command." },
        { imgId: 207, payload: "providing a localized UHF/VHF relay for ground exercises", instruction: "You are holding steady over the sector as a UHF/VHF relay for ground exercises. Watch your fuel and monitor your instruments and oxygen." }
    ],
    'tacticalJet-MIL': [
        { imgId: 208, payload: "gathering passive telemetry data", instruction: "You are gathering passive telemetry data today. Fly the filed route exactly so the onboard equipment can triangulate regional signal traffic." },
        { imgId: 209, payload: "providing a target profile for ground-based early warning systems", instruction: "You are providing a target profile for ground early warning systems. Hold the altitude and airspeed in your flightplan so the stations can calibrate their radar returns." },
        { imgId: 210, payload: "intercepting unidentified radar contacts", instruction: "You are intercepting unidentified radar contacts. Keep speed up and watch the tactical displays for vectored intercepts." },
        { imgId: 211, payload: "conducting a cooperative cross-service nav exercise", instruction: "You are on a cooperative cross-service nav exercise. Match profiles with the allied assets — timing has to be spot-on for the rendezvous." },
        { imgId: 212, payload: "verifying long-range optical and radar sensor integrity", instruction: "Ground stations need a clean target for tracking telemetry. Keep the airframe smooth — the pods hate vibration." },
        { imgId: 213, payload: "re-validating primary approach vectors", instruction: "You are re-validating primary approach vectors today. Non-precision approach practice — log the navaids properly and fly it by the book." },
        { imgId: 214, payload: "repositioning airframes for off-cycle maintenance", instruction: "You are on a ferry flight for off-cycle maintenance. Watch your temps and keep the engines happy." },
        { imgId: 215, payload: "conducting a two-ship proficiency transit", instruction: "You are on a two-ship proficiency transit. Keep wingman separation inside the limits through climb and cruise — no surprises." },
        { imgId: 216, payload: "conducting a handling and proficiency check", instruction: "You are conducting a handling and proficiency check. Fly the filed route with sharp energy management and respect the floor altitudes in the simulated combat phase." },
        { imgId: 217, payload: "executing a high-speed, terrain-masking profile", instruction: "You are executing a terrain-masking profile today. Terrain-following or strict visual low-level — hold 250 feet AGL through the corridor and watch for birds." },
        { imgId: 218, payload: "providing support for regional exercises", instruction: "You are Red Air today. Fly the briefed intercept vectors, test friendly radar response, acknowledge sim contacts, then proceed to destination.", excludedAircraft: ["B461_MIL"] },
        { imgId: 219, payload: "ferrying to a regional aviation festival", instruction: "You have been instructed to be on the staging grounds before sunset. Cruise power to spare the engines — expect a crowd watching your arrival." },
        { imgId: 220, payload: "conducting aerial refuelling approach practice", instruction: "You are conducting aerial refuelling approach practice. Fly the assigned route and hold airspeed and altitude per your flightplan the whole way.", excludedAircraft: ["SPIT", "BF109", "F6F", "P38"] }
    ],
    'reconnaissance-MIL': [
        { imgId: 220, missionType: 32, payload: "conducting aerial refuelling approach practice", instruction: "You are conducting aerial refuelling approach practice. Fly the assigned route and hold airspeed and altitude per your flightplan the whole way.", allowedAircraft: STRATEGIC_RECON_AIRCRAFT, excludedAircraft: ["SPIT", "BF109", "F6F", "P38", "FW08", "A6M5"] },
        { imgId: 221, missionType: 32, payload: "conducting a transit reconnaissance sortie", instruction: "You are flying departure to destination on the assigned recon route. Hold altitude and airspeed so the sensors collect continuous imagery along the corridor.", allowedAircraft: STRATEGIC_RECON_AIRCRAFT },
        { imgId: 222, missionType: 32, payload: "mapping the assigned transit corridor", instruction: "You are mapping the assigned transit corridor today. Fly direct, hold a steady track and altitude and let the mapping systems build a clean picture.", allowedAircraft: STRATEGIC_RECON_AIRCRAFT, preferredAircraft: VULCAN_RECON_PREFERRED },
        { imgId: 223, missionType: 32, payload: "photographing designated areas along the route", instruction: "You are photographing designated areas along the route. Match the briefed headings and timings so analysts can sync the imagery to the mission clock.", allowedAircraft: STRATEGIC_RECON_AIRCRAFT, preferredAircraft: VULCAN_RECON_PREFERRED },
        { imgId: 249, missionType: 32, payload: "conducting a two-ship formation proficiency transit", instruction: "You are on a two-ship formation transit, departure to destination. Keep wingman spacing inside limits through the climb and cruise.", allowedAircraft: STRATEGIC_RECON_AIRCRAFT, preferredAircraft: VULCAN_RECON_PREFERRED },
        { imgId: 250, missionType: 32, payload: "conducting aerial refuelling approach practice", instruction: "You are conducting aerial refuelling approach practice. Hold airspeed and altitude as briefed and do not break another refuelling nozzle.", allowedAircraft: STRATEGIC_RECON_AIRCRAFT, excludedAircraft: ["SPIT", "BF109", "F6F", "FW08", "P38"] }
    ],
    gliderOps: [
        { imgId: 224, payload: "flying a club cross-country task between glider fields", instruction: "You will launch from {dep_field} and work lift toward {dest_field}. Read the sky — developing cumulus marks the thermals, with puffy tops and dark flat bases. Give decaying wispy cloud a wide berth. Stay VFR and arrive with height for a normal circuit." },
        { imgId: 225, isLocal: true, payload: "building local soaring currency above {dep_field}", instruction: "Stay in the local area above {dep_field}. Practice thermalling, position reports and clean circuit entries. Under developing cumulus, core the strongest lift. Recover to the glider strip when your block time expires." },
        { imgId: 226, payload: "working available lift toward {dest_field}", instruction: "You are working whatever lift the day offers between {dep_field} and {dest_field}. Use thermals under growing Cu, slope lift or cloud streets where you can. Stay clear of lee turbulence and do not press into sink without a landing option." },
        { imgId: 227, payload: "conducting a dual instructional sortie from {dep_field}", instruction: "You have a student aboard for handling and lookout practice. Demonstrate energy management and circuit work, and talk through how you read the sky as you fly. Keep the ride smooth and verbalize every decision." },
        { imgId: 228, payload: "ferrying under power from {dep_field} to {dest_field}", instruction: "The club needs this glider repositioned from {dep_field} to {dest_field}. Climb to a safe altitude, shut down to soar when you can and keep enough battery or fuel for a go-around reserve at destination." },
        { imgId: 229, payload: "flying a contest-style practice task", instruction: "You are flying a practice speed task from {dep_field} to {dest_field}. Work your height band, plan turns before weak lift and use cloud streets to cover ground. Progress by soaring technique, not minimum time under engine power." }
    ]
};

const names = ["Tom Cruise", "Dwayne Johnson", "Leonardo DiCaprio", "Scarlett Johansson", "Margot Robbie", "Zendaya", "Tom Holland", "Robert Downey Jr.", "Brad Pitt", "Angelina Jolie", "Will Smith", "Pedro Pascal", "Timothée Chalamet", "Florence Pugh", "Ryan Reynolds", "Hugh Jackman", "Chris Hemsworth", "Keanu Reeves", "Meryl Streep", "Jackie Chan"];
const athletes = ["Cristiano Ronaldo", "Lionel Messi", "LeBron James", "Stephen Curry", "Simone Biles", "Tiger Woods", "Lewis Hamilton", "Patrick Mahomes", "Shohei Ohtani", "Caitlin Clark", "Novak Djokovic", "Rafael Nadal", "Usain Bolt", "Kylian Mbappé", "Virat Kohli", "Serena Williams", "Michael Phelps", "Kevin Durant", "Carlos Alcaraz", "Katie Ledecky"];
const teams = ["Real Madrid", "Barcelona", "Manchester United", "Manchester City", "Bayern Munich", "Paris Saint-Germain", "Liverpool", "Los Angeles Lakers", "Golden State Warriors", "Boston Celtics", "New York Yankees", "Los Angeles Dodgers", "Kansas City Chiefs", "Dallas Cowboys", "San Francisco 49ers", "Ferrari", "Mercedes F1 Team", "Mumbai Indians", "All Blacks", "Toronto Maple Leafs"];
const musician = ["Taylor Swift", "Beyoncé", "Drake", "The Weeknd", "Billie Eilish", "Bad Bunny", "Ed Sheeran", "Adele", "Justin Bieber", "Bruno Mars", "Dua Lipa", "Rihanna", "Lady Gaga", "Chris Martin", "Eminem", "Harry Styles", "Olivia Rodrigo", "Post Malone", "Kendrick Lamar", "BTS"];
const medCargo = ["specialized surgical tools", "temperature-sensitive donor organs", "blood plasma reserves", "advanced diagnostic equipment", "rare antivenom vials", "experimental vaccine cultures"];
const industry = ["Tech", "Energy", "Finance", "Pharmaceutical", "Real Estate", "Automotive", "Aerospace", "Telecommunications"];
const vipType = ["global diplomat", "tech billionaire", "renowned film director", "royal family member", "high-profile whistleblower", "media tycoon"];
const sciFi = ["geometric anomaly", "unexplained localized magnetic distortion", "perfectly circular crop depression", "unidentified pulsating light source", "rapidly expanding sinkhole"];
const cargoType = ["lithium-ion batteries", "drilling equipment", "server racks", "luxury vehicle parts", "stage rigging", "humanitarian rations"];

const preFlightQuotes = [
{ text: "When once you have tasted flight, you will forever walk the earth with your eyes turned skyward, for there you have been, and there you will always long to return.", author: "Not Leonardo DaVinci" },
{ text: "Man must rise above the Earth, to the top of the atmosphere and beyond, for only thus will he fully understand the world in which he lives.", author: "paraphrase of a concept from Plato's Phaedo" },
{ text: "I fly because it releases my mind from the tyranny of petty things.", author: "Antoine de Saint-Exupery" },
{ text: "The desire to fly is an idea handed down to us by our ancestors who, in their grueling travels across trackless lands in prehistoric times, looked enviously on the birds soaring freely through space, at full speed, above all obstacles, on the infinite highway of the air.", author: "Wilbur Wright" },
{ text: "Sometimes, flying feels too God-like to be attained by man. Sometimes, the world from above seems too beautiful, too wonderful, too distant for human eyes to see.", author: "Charles A. Lindbergh" },
{ text: "Pilots are a rare kind of human. They leave the ordinary surface of the word, to purify their soul in the sky, and they come down to earth, only after receiving the communion of the infinite.", author: "Jose Maria Velasco Ibarra" },
{ text: "Airspeed, altitude, and brains. Two are always needed to successfully complete the flight.", author: null },
{ text: "Both optimists and pessimists contribute to our society. The optimist invents the airplane and the pessimist the parachute.", author: "Gil Stern" },
{ text: "If black boxes survive air crashes, why don’t they make the whole plane out of that stuff?", author: "George Carlin" },
{ text: "You’ve never been lost until you’ve been lost at Mach 3.", author: "Paul F. Crickmore" },
{ text: "Learn from the mistakes of others. You won’t live long enough to live all of them yourself.", author: null },
{ text: "You start with a bag full of luck and an empty bag of experience. The trick is to fill the bag of experience before you empty the bag of luck.", author: null },
{ text: "Good judgment comes from experience. Unfortunately, the experience usually comes from bad judgment.", author: null },
{ text: "There are old pilots and there are bold pilots. However, there are no old, bold pilots.", author: null },
{ text: "The engine is the heart of an airplane, but the pilot is its soul.", author: "Walter Raleigh" },
{ text: "Aviation is proof that given the will, we have the capacity to achieve the impossible.", author: "Eddie Rickenbacker" },
{ text: "Flying is more than a sport and more than a job; flying is pure passion and desire.", author: "General Adolf Galland" },
{ text: "The airplane stands for freedom, for joy, for the power to understand.", author: "Richard Bach" },
{ text: "We who fly do so for the love of flying.", author: "Cecil Day-Lewis" },
{ text: "Adventure is worthwhile in itself.", author: "Amelia Earhart" },
{ text: "Flying is hypnotic and all pilots are victims to the spell.", author: "Ernest K. Gann" },
{ text: "Life is like a landscape. You live in the midst of it but can describe it only from the vantage point of distance.", author: "Charles Lindbergh" },
{ text: "I owned the world that hour as I rode over it – free of the earth, free of the mountains, free of the clouds, but how inseparably I was bound to them.", author: "Charles Lindbergh" },
{ text: "Real freedom lies in wildness, not in civilization.", author: "Charles Lindbergh" },
{ text: "Flying is learning how to throw yourself at the ground and miss.", author: "Douglas Adams" }
];
if (typeof globalThis !== "undefined") {
    globalThis.SCENARIO_JOB_TITLES = SCENARIO_JOB_TITLES;
    globalThis.missionMatrix = missionMatrix;
    globalThis.scenarioDB = scenarioDB;
    globalThis.MIL_AIRLIFTER_CIVIL_TYPES = MIL_AIRLIFTER_CIVIL_TYPES;
    globalThis.getMilAirlifterCivilScenarioImgIds = getMilAirlifterCivilScenarioImgIds;
    globalThis.A400_CIVIL_FREIGHT_SCENARIO_IMGIDS = A400_CIVIL_FREIGHT_SCENARIO_IMGIDS;
}