const RESTRICTED_JET_MISSION_TYPES = ["A319", "E190", "E195", "RJ70", "RJ85", "RJ1H", "RJ1F", "B461", "B462", "B462_QT", "B463", "B463_QT"];
const EGLC_JET_MISSION_TYPES = RESTRICTED_JET_MISSION_TYPES.concat(["F70"]);
const REGIONAL_JET_FREIGHTERS = ["B462_QT", "B463_QT", "RJ1F"];
const MAINLINE_JET_FREIGHTERS = ["B738_BCF", "B738_BDSF", "B72F"];
const SMALL_GA_TRAINERS = ["PA28", "P28A", "PA38"];
const VULCAN_RECON_PREFERRED = ["VULC"];
const TACTICAL_JET_MISSION_TYPES = ["F14A", "F14B", "HAWK", "JAGR", "TOR"];
const STRATEGIC_RECON_AIRCRAFT = ["VULC", "C160", "C130", "P38", "SPIT", "BF109", "F6F", "FW08", "A6M5"].concat(TACTICAL_JET_MISSION_TYPES);
const CELEBRITY_BIZ_JET_PREFERRED = ["STAR", "P180", "C700", "C680", "C750", "E55P", "FA50", "LJ35", "HDJT", "SF50"];
const CELEBRITY_VIP_SCENARIO_WEIGHT_MULT = 5;

// Military airlifters (CIVIL_OK): civilian heavy-freight scenarios only — military templates unchanged.
const MIL_AIRLIFTER_CIVIL_TYPES = ["A400", "C130", "C160"];
const MIL_AIRLIFTER_CIVIL_BASE_SCENARIO_IMGIDS = [104, 110, 111, 115, 116, 120, 121, 122, 123];
const MIL_AIRLIFTER_CIVIL_EXTRA_SCENARIO_BY_TYPE = { C160: [114] };
const MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT = ["A400", "C130", "C160"];
const MIL_AIRLIFTER_EXCLUDED_OVERNIGHT_PARCELS = ["A400", "C130"];
function getMilAirlifterCivilScenarioImgIds(aircraftType) {
    if (!MIL_AIRLIFTER_CIVIL_TYPES.includes(aircraftType)) return null;
    const extra = MIL_AIRLIFTER_CIVIL_EXTRA_SCENARIO_BY_TYPE[aircraftType] || [];
    return MIL_AIRLIFTER_CIVIL_BASE_SCENARIO_IMGIDS.concat(extra);
}
// Back-compat alias for audits referencing the A400 base list.
const A400_CIVIL_FREIGHT_SCENARIO_IMGIDS = MIL_AIRLIFTER_CIVIL_BASE_SCENARIO_IMGIDS;

const missionMatrix = [
    // UNIQUE MISSION TEMPLATES — one mission (imgId) each via pool "uniqueMissions"
    { type: 1, name: "Noise Abatement Departure (EGLC)", detail: "Execute a steep climb out of EGLC.", pool: "uniqueMissions", weight: 1,  requiredDep: "EGLC", allowedAircraft: EGLC_JET_MISSION_TYPES, maxMTOW: 75500 },
    { type: 2, name: "Noise Abatement Departure (EGNS)", detail: "Execute a steep climb out of EGNS.", pool: "uniqueMissions", weight: 1, requiredDep: "EGNS", allowedAircraft: RESTRICTED_JET_MISSION_TYPES, maxMTOW: 75500 },
    { type: 3, name: "Ponte Aérea Commuter", detail: "Departing SBRJ requires precision due to the short runway and surrounding terrain. Utilize maximum takeoff thrust and be prepared for an immediate tight climbing turn after rotation.", pool: "uniqueMissions", weight: 1, requiredDep: "SBRJ", allowedAircraft: ["A319", "E190", "E195"], maxMTOW: 75500 },
    { type: 4, name: "Classic Cross-Country Rally", detail: "Pushing the Comanche to its cruise limits today. Monitor your cylinder head temperatures and carefully manage your mixture to optimize fuel burn for the rally.", pool: "uniqueMissions", weight: 1, allowedAircraft: ["PA24"] },
	{ type: 5, name: "High-Altitude Express", detail: "Take advantage of the aircraft's pressurization and climb rate to get above the regional weather systems. Keep your block time tight.", pool: "uniqueMissions", weight: 1, minAlt: 10000, rules: "IFR", allowedAircraft: ["C414", "B58T", "BE60", "STAR", "P180", "TBM8"] },
    { type: 7,  name: "Whisperjet Operations", detail: "Your airframe was picked specifically for its quiet acoustic footprint. Adhere strictly to the descent profile and avoid late configuration changes.", pool: "uniqueMissions", weight: 1, allowedAircraft: ["RJ1F", "B462_QT", "B463_QT", "B462_MIL"] },
    { type: 8,  name: "Research Observation Flight", detail: "A local university needs optical data on changing topography. Maintain a steady track at low altitudes. Monitor your radial engine temperatures carefully.", pool: "uniqueMissions", weight: 40, allowedAircraft: ["U16"] },
    { type: 9,  name: "Remote Outpost Resupply", detail: "You're utilizing the Albatross's heavy lift capacity and rugged landing gear today. Execute a standard approach, but be mindful of the heavy control inputs required for this vintage airframe.", pool: "uniqueMissions", weight: 40, allowedAircraft: ["U16"] },
    { type: 10, name: "Albatross Patrol Run", detail: "Flying a patrol route. Keep your eyes outside the cockpit, maintain visual contact with the terrain where possible, and execute smooth turns.", pool: "uniqueMissions", weight: 40, allowedAircraft: ["U16"] },
    { type: 11, name: "Survey Platform", detail: "A local university needs optical data on changing topography. Maintain a steady track at low altitudes. Monitor your radial engine temperatures carefully.", pool: "uniqueMissions", weight: 40, allowedAircraft: ["U16"] },
    { type: 12, name: "Remote Supply Drop", detail: "You're utilizing the Albatross's heavy lift capacity and rugged landing gear today. Execute a standard approach, but be mindful of the heavy control inputs required for this vintage airframe.", pool: "uniqueMissions", weight: 40, allowedAircraft: ["U16"] },
    { type: 13, name: "Commemorative SAR Demo", detail: "Flying a commemorative SAR route to honor the crews who operated these flying boats. Keep your eyes outside the cockpit, maintain visual contact with the terrain, and execute smooth, sweeping turns.", pool: "uniqueMissions", weight: 40, allowedAircraft: ["U16"] },
    // DYNAMIC MASTER TEMPLATES - no image required
    { type: 14, name: "Commercial Service", pool: "commercial", weight: 15, allowedClasses: ["JET", "TURBO"] },
    { type: 15, name: "Regional Commuter", pool: "commercial-regional", weight: 15, allowedClasses: ["TURBO", "JET"] },
    { type: 16, name: "Executive Charter", pool: "executive", weight: 15, allowedClasses: ["BIZ JET", "TURBO", "HELI"], minPaxSeats: 2, minPaxSeatsAppliesTo: ["HELI"], excludedAircraft: SMALL_GA_TRAINERS.concat(MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT) },
    { type: 17, name: "Light Freight Ops", pool: "lightFreight", weight: 15, allowedClasses: ["GA", "TURBO", "BIZ JET", "JET"], maxMTOW: 5000, maxMTOWAppliesTo: ["GA", "TURBO"], excludedAircraft: MAINLINE_JET_FREIGHTERS },
    { type: 18, name: "Heavy Cargo Transport", pool: "heavyFreight", weight: 15, allowedClasses: ["JET", "TURBO"], minCargo: 2000, excludedAircraft: ["VULC"] },
    { type: 19, name: "Medical Relay", pool: "medical", weight: 15, allowedClasses: ["GA", "TURBO", "HELI", "BIZ JET"] },
    { type: 20, name: "Aerial Survey", pool: "surveyServices", weight: 15, allowedClasses: ["GA", "HELI"], excludedAircraft: ["C700"], maxMTOW: 8000 },
    { type: 21, name: "Rotary Wing Operations", pool: "helicopterOps-CIV", weight: 15, allowedClasses: ["HELI"], civilianOnly: true },
    { type: 22, name: "Local Rotary Wing Operations", pool: "helicopterOps-CIV", weight: 15, allowedClasses: ["HELI"], isLocal: true, civilianOnly: true },
    { type: 23, name: "Tactical Sortie", pool: "tacticalJet-MIL", weight: 15, allowedClasses: ["JET", "WARBIRD", "HELI"], militaryOnly: true, tacticalOnly: true },
    { type: 24, name: "Military Logistics", pool: "militaryTransit-MIL", weight: 15, allowedClasses: ["TURBO", "JET", "HELI", "WARBIRD"], militaryOnly: true },
    { type: 25, name: "Heritage Flight", pool: "vintageOps", weight: 15, allowedClasses: ["WARBIRD", "GA", "TURBO", "JET"] },
    { type: 26, name: "Classic Airliner Charter", pool: "vintageAirliner", weight: 40, allowedAircraft: ["DC6B"], excludedAircraft: ["DC6A"] },
    { type: 27, name: "Weather Ops", pool: "highAltServices", weight: 15, allowedClasses: ["TURBO", "JET"], excludedAircraft: ["C700", "STAR", "P180"] },
    { type: 28, name: "Air Taxi", pool: "lightPax", weight: 15, allowedClasses: ["GA", "TURBO", "BIZ JET", "HELI"], maxMTOW: 6000, maxMTOWAppliesTo: ["GA", "TURBO", "HELI"], excludedAircraft: SMALL_GA_TRAINERS },
    { type: 29, name: "Mil-Cargo Ops", pool: "heavyFreight-MIL", weight: 15, allowedClasses: ["JET", "TURBO", "HELI"], minCargo: 4000, militaryOnly: true, excludedAircraft: ["VULC"] },
    { type: 30, name: "Military Heli-Ops", pool: "helicopterOps-MIL", weight: 15, allowedClasses: ["HELI"], militaryOnly: true },
    { type: 31, name: "Base Staff Shuttle", pool: "helicopterOps-MIL", weight: 15, allowedClasses: ["HELI"], militaryOnly: true, isLocal: true },
    { type: 32, name: "Strategic Recon.", pool: "reconnaissance-MIL", weight: 20, allowedClasses: ["JET", "WARBIRD", "TURBO"], militaryOnly: true },
    { type: 33, name: "Vintage Propliner Freight", detail: "Classic propliner freight for the DC-6A. Keep your RPMs synced, mind the cowl flaps, and remember that descending takes planning when you don't have speedbrakes.", pool: "vintageProplinerFreight", weight: 40, allowedAircraft: ["DC6A"], excludedAircraft: ["DC6B"], minCargo: 2000 },
    { type: 34, name: "Gliding Operations", pool: "gliderOps", allowedClasses: ["GLIDER"], rules: "VFR/Scenic" },
    { type: 39, name: "Regional Freight Pulse", pool: "regionalFreight", weight: 15, allowedClasses: ["JET", "TURBO"] }
];

/** Brief contract-board headline per scenario imgId (from scenario-job-titles.json). */
const SCENARIO_JOB_TITLES = {
    1: "EGLC Steep Climb",
    2: "EGNS Steep Climb",
    3: "Ponte Aérea Run",
    4: "Cross-Country Rally",
    5: "High-Altitude Express",
    7: "Whisperjet Run",
    8: "Geological Research",
    9: "Outpost Supply Run",
    10: "Morning Patrol",
    11: "Survey Flight",
    12: "Supply Drop",
    13: "SAR Operations",
    14: "Sports Team Charter",
    15: "Holiday Charter",
    16: "Recovery Sector",
    17: "Hub Link",
    18: "Tourist Transport",
    19: "Convention Charter",
    20: "Holiday Route",
    21: "Network Recovery",
    22: "Corporate Summit",
    23: "Flagship Route",
    24: "Scheduled Sector",
    25: "Standard Commercial Route",
    26: "Early Bird Business Shuttle",
    27: "Student Charter",
    28: "Symphony Orchestra",
    29: "Exchange Students",
    30: "Company Seminar",
    31: "Championship Final",
    32: "Sun-Seekers",
    33: "Regional Hop",
    34: "Regional Sector",
    35: "Network Support",
    36: "Late-Evening Commuter",
    37: "Weather Recovery",
    38: "Regional Holiday Run",
    39: "Regional Outage",
    40: "Corporate Summit",
    41: "Busy Feeder",
    42: "Hub Feeder",
    43: "Student Transfer",
    44: "Staff Charter",
    45: "VIP Charter",
    46: "Sports Charter",
    47: "Executive Negotiation",
    48: "Executive Offsite",
    49: "State Delegation",
    50: "VIP Conference Charter",
    51: "Executive Facility Run",
    52: "Fractional Owner",
    53: "Investor Roadshow",
    54: "Witness Transport",
    55: "Private Buyer",
    56: "Crisis Counsel",
    57: "First-Class Feline",
    58: "Champagne Shopping Run",
    59: "Weekend Retreat",
    60: "Business Commute",
    61: "Stadium Charter",
    62: "Spiritual Retreat",
    63: "Championship Charter",
    64: "VIP Film Premiere",
    65: "Club Executive",
    66: "Medical Team Transport",
    67: "VIP Private Gala",
    68: "Executive Support",
    69: "Patient Airlift",
    70: "Medical Transport",
    71: "Patient Transport",
    72: "Diplomatic Files",
    73: "Prototype Hardware",
    74: "Protected Species",
    75: "Conservation Team",
    76: "Digital Masters",
    77: "Rare Manuscripts",
    78: "AOG Component",
    79: "Regional Medical Cargo",
    80: "Medical Cargo",
    81: "Medical Supplies",
    82: "Farm Produce",
    83: "Regional Overnight",
    84: "Regional Mail",
    85: "Essential Supplies",
    86: "Regional Supplies",
    87: "Regional Lab Samples",
    88: "Morning Paper run",
    89: "Premium Seafood",
    90: "Acting up",
    91: "Rare Components",
    92: "Machinery Parts",
    93: "Ferry flight",
    94: "Mail Run",
    95: "Community Supply",
    96: "Night Express",
    97: "Priority Parcels",
    98: "Overnight Freight",
    99: "Priority Medical Freight",
    100: "Lab Samples",
    101: "Field Machinery",
    102: "Regional Business Supplies",
    103: "Late Night Regional",
    104: "Relief Supplies",
    105: "High Street Supplies",
    106: "Museum Artifacts",
    107: "Cargo Delivery",
    108: "Luxury Vehicles",
    109: "Supercar Delivery",
    110: "Oilfield Equipment",
    111: "Avionics Bay",
    112: "Premium Perishables",
    113: "Consumer Electronics",
    114: "Overnight Parcels",
    115: "Secure Bullion",
    116: "Heavy dot com",
    117: "Overnight Cargo",
    118: "Warehouse goods",
    119: "Formula One Chassis",
    120: "Heavy Machinery",
    121: "Industrial Generator",
    122: "Replacement Turbine",
    123: "Server Rack Delivery",
    124: "Misinformation",
    125: "Pipeline Survey",
    126: "Crop Inspection",
    127: "Expansion Zone",
    128: "Subsurface Mapping",
    129: "Storm Assessment",
    130: "LIDAR Assessment",
    131: "High-end property shoot",
    132: "Anomaly Survey",
    133: "Missing Vehicle Search",
    134: "Staff Shuttle",
    135: "Currency Flight",
    136: "Consultant Hop",
    137: "Community Link",
    138: "Private Schedule",
    139: "VIP Spiritual Retreat",
    140: "Romantic twilight flight",
    141: "Missed Connection",
    142: "Family Link",
    143: "Honeymoon Charter",
    144: "Medical Examiner",
    145: "The Gentleman's Estate",
    146: "Ferry Delivery",
    147: "Weather Ops",
    148: "Storm Chasers",
    149: "Airshow Display",
    150: "Handicap Race",
    151: "Vintage Airframe ferry",
    152: "Chase Plane (not that one)",
    153: "Commemorative Fly-by",
    154: "Keeping current",
    155: "Restoration Delivery",
    156: "Aviation Festival",
    157: "Remembrance Flight",
    158: "Vintage Freight",
    159: "Live Agricultural",
    160: "Classic Heavy Lift",
    161: "Pallet Freight",
    162: "Overnight Liner",
    163: "Holiday Liner",
    164: "Executive Extraction",
    165: "Matchday Fans",
    166: "Classic Shuttle",
    167: "Scenic Hop",
    168: "Photo Survey",
    169: "Traffic Watch",
    170: "On-Demand Charter",
    171: "Highway Extraction",
    172: "SAR Ops",
    173: "Aerial Overwatch",
    174: "Property Developers",
    175: "Industrial Support",
    176: "Wildlife Tracking",
    177: "Executive Shuttle",
    178: "Live Event Monitoring",
    179: "Cinematic Tracking Shots",
    180: "Put that in your pipe",
    181: "High Tension Cleaning",
    182: "Sensitive Documents",
    183: "Shiny but what is it?",
    184: "Tactical Vehicle Transport",
    185: "Defense Component Transport",
    186: "Sensitive Hardware",
    187: "Technical Spares",
    188: "AOG Parts for Inspection",
    189: "Tactical Cargo Delivery",
    190: "Refugee Relief Supply",
    191: "Ground Team Deployment",
    192: "Perimeter Survey",
    193: "VIP Base Tour",
    194: "SAR Training",
    195: "Observation Post Resupply",
    196: "Command Briefing",
    197: "Telemetry Transfer",
    198: "Unmarked Containers",
    199: "Relocating Defense Personnel",
    200: "Strategic repositioning",
    201: "Navigation Exercise",
    202: "Tactical Escort",
    203: "Diplomatic Pouch",
    204: "Cryogenic xenobiological tissue transfer",
    205: "SAR Support",
    206: "Surface Anomaly",
    207: "Comms Relay",
    208: "Passive Telemetry",
    209: "Radar Calibration",
    210: "Intercept Profile",
    211: "Cross-Service Exercise",
    212: "Sensor Check",
    213: "Approach Vector Testing",
    214: "Maintenance Ferry",
    215: "Two-Ship Transit",
    216: "Proficiency Check",
    217: "Terrain Masking",
    218: "Red Air Support",
    219: "Festival Ferry",
    220: "Tanker Practice",
    221: "Transit Recon",
    222: "Corridor Mapping",
    223: "Route Photography",
    224: "Cross-Country Task",
    225: "Soaring Currency",
    226: "Lift me up",
    227: "Instructional Sortie",
    228: "Powered Ferry",
    229: "Practice Task",
    249: "Formation Transit",
    250: "Tanker Practice"
};

const scenarioDB = {
    uniqueMissions: [
        { imgId: 1, missionType: 1, payload: "Noise Abatement Departure (EGLC)", instruction: "EGLC has you on the noise-abatement departure today. Fly the steep-climb profile and keep it clean for the monitors below." },
        { imgId: 2, missionType: 2, payload: "Noise Abatement Departure (EGNS)", instruction: "Today's EGNS departure follows the noise-abatement profile. Fly the steep climb and keep it clean for the community underneath." },
        { imgId: 3, missionType: 3, payload: "Ponte Aérea Commuter", instruction: "The Ponte Aérea run leaves SBRJ today. Use max thrust, expect a tight climbing turn right after rotation and watch the terrain closely." },
        { imgId: 4, missionType: 4, payload: "Classic Cross-Country Rally", instruction: "This cross-country rally will push the Comanche hard. Watch the cylinder-head temps and manage the mixture so you do not cook the engine on the trip." },
        { imgId: 5, missionType: 5, payload: "High-Altitude Express", instruction: "You have pressurization and climb rate to work with today. Use both to get above the regional weather and keep your block time tight." },
        { imgId: 7, missionType: 7, payload: "Whisperjet Operations", instruction: "You were picked for this run because you are flying the 'Whisperjet'. Stick to the descent profile and be sure to lower flaps and gear in time for a clean landing." },
        { imgId: 8,   missionType: 8,  payload: "flying researchers over surface anomalies", instruction: "A local university wants optical data on changing topography below. Hold a steady low track and watch those radial engine temps on the Albatross.", allowedAircraft: ["U16"] },
        { imgId: 9,   missionType: 9,  payload: "delivering bulk provisions to a distant outpost", instruction: "Bulk provisions are bound for a distant outpost today. The Albatross is heavy and the equipment is getting old. Fly a standard approach and expect firm control inputs.", allowedAircraft: ["U16"], minCargoLoadFactor: 0.70 },
		{ imgId: 10,  missionType: 10, payload: "Albatross Patrol Run", instruction: "Today's Albatross patrol needs eyes outside the cockpit. Stay in visual contact with the terrain where you can and fly smooth turns.", allowedAircraft: ["U16"] },
        { imgId: 11, missionType: 11, payload: "Survey Platform", instruction: "Today you are flying a research team to their destination. Their equipment is sensitive to being thrown around, so fly a gentle landing and no steep turns.", allowedAircraft: ["U16"] },
        { imgId: 12, missionType: 12, payload: "Remote Supply Drop", instruction: "The team at your destination is waiting on bulk provisions. Fly a controlled approach and check landing conditions before you arrive.", allowedAircraft: ["U16"], minCargoLoadFactor: 0.70 },
        { imgId: 13, missionType: 13, payload: "Commemorative SAR Demo", instruction: "This commemorative route honours the crews who operated these flying boats. Keep your eyes outside, stay low where you can and fly smooth, sweeping turns.", allowedAircraft: ["U16"] }
    ],
        commercial: [
        { imgId: 14, payload: "flying {team} to their next fixture", instruction: "{team}, the coaching staff and their medical kit are aboard. Keep the climb and descent gentle so nobody is bouncing around before the whistle blows.", weight: 3 },
        { imgId: 15, payload: "flying a holiday charter group", instruction: "The cabin is full of holiday passengers on annual leave. Give them a steady ride and let their holidays start early." },
        { imgId: 16, payload: "recovering passengers after widespread weather groundings", instruction: "Yesterday's storms grounded half the network. You have a full cabin of tired passengers who just need to get where they were meant to be.", weight: 3 },
        { imgId: 17, payload: "transporting travellers between hubs", instruction: "This is a scheduled hub link: heavy metal and big airports. Fly the filed route and settle her early on the approach." },
        { imgId: 18, payload: "transporting tourists to their destination", instruction: "The cabin is packed with tourists in holiday mood, and the schedule is relentless. Hit the block times or you will hear about it at the gate." },
        { imgId: 19, payload: "ferrying professionals to a major tech convention", instruction: "Tech professionals will have their laptops open from pushback. Keep the cruise smooth so they can get their work done on time.", weight: 3 },
        { imgId: 20, payload: "operating a high-capacity holiday route", instruction: "The sky is busy on this peak-season holiday route. Listen for holds, watch the fuel and do not get caught short if ATC stacks you up." },
        { imgId: 21, payload: "recovering a diverted flight after a regional system outage", instruction: "The passengers have been stuck for hours after the network went down. Climb smoothly, plan ahead during Cruise and call for Top of descent early. Time to get these people back home." },
        { imgId: 22, payload: "ferrying a corporate group to an annual summit", instruction: "A corporate group is in the back after a long week away at a global offsite. No need for chatty PAs tonight. Fly a quiet, smooth sector and bring these folks back home." },
        { imgId: 23, payload: "operating the airline's most popular route", instruction: "Today's sector is the airline's flagship route. Fly quickly and safely and expect a quick turnaround once the passengers have disembarked and you have refuelled." },
        { imgId: 24, payload: "operating a scheduled commercial sector", instruction: "The clock is against you on this scheduled sector. Ask for priority on the approach, aim for vectors to finals, and get the passengers offloaded as soon as you block in." },
        { imgId: 25, payload: "operating a standard commercial sector", instruction: "Ordinary line flying is on the board today. Fly it by the book and keep to the schedule. This is what you trained for. You are in charge of a $350 million aircraft, enjoy the flight." },
        { imgId: 26, payload: "shuttling morning business travelers from hub to hub", instruction: "You are shuttling morning business passengers between hubs. ATC has a full sky today, so hold the assigned speed and plan ahead. Call for top of descent and who knows, you might even get vectored to the top of the glideslope if you're lucky." },
        { imgId: 27, payload: "transporting university students to a massive event", instruction: "University students have taken over your cabin on their way to a massive event. Expect lots of overhead cabins opening and closing and, if it gets rowdy back there, send in the cavalry and turn the seat belt signs on." },
        { imgId: 28, payload: "transporting a full symphony orchestra and their instruments", instruction: "A touring symphony orchestra need to get to their next concert. You now have a hold full of instrument cases that do not bounce well. Fly a clean departure and watch the weather radar for turbulence." },
        { imgId: 29, payload: "flying a group of exchange students to their host country", instruction: "A cabin of excited exchange students is headed to their host families. Nothing fancy is needed today, just a safe, smooth flight and no delays.", weight: 3 },
        { imgId: 30, payload: "transporting company personnel to a seminar", instruction: "Company personnel are headed to a major post-merger integration seminar. The cabin is full and it's up to you to get the workforce to their destination on time and in one piece." },
        { imgId: 31, payload: "flying fans to a major championship final", instruction: "You have a lively team of sports fans filling the cabin today. Warn the crew to steel themselves as some fans are already celebrating in row twelve." },
        { imgId: 32, payload: "transporting retirees to warmer climates for the winter", instruction: "Retired sun-seekers fill every seat. Give them a soft rotation, a soft landing and don't spill their Bloody Marys with steep turns." }
    ],
    'commercial-regional': [
        { imgId: 33, payload: "flying a short regional commuter hop", instruction: "This is a short regional sector. The cabin is full of young professionals on their way to meetings. The wheels of commerce keep turning thanks to your skills as a pilot." },
        { imgId: 34, payload: "working a string of short sectors with fast turns", instruction: "A string of short sectors is on today's roster. Keep the cabin cool on the ground, use Hotel mode if your airframe has it and stay clear of developing weather fronts." },
        { imgId: 35, payload: "keeping a rural town linked into the network", instruction: "This run matters to the towns it serves. Stick to the schedule as plenty of passengers are counting on a connection at the other end." },
        { imgId: 36, payload: "flying a quiet late-evening commuter sector", instruction: "Tonight's late commuter sector should be a quiet one. The sky is empty tonight. Climb efficiently and do not waste fuel. The company is clamping down hard and wants to save money." },
        { imgId: 37, payload: "recovering passengers after widespread weather groundings", instruction: "You have a full cabin of tired short-haul passengers who just want to get back home after yesterday's groundings." },
        { imgId: 38, payload: "taking holidaymakers to their destination", instruction: "Every seat is taken on this regional sector. Hit the block times and tell the crew that the passengers are ready to start their holiday when the doors open." },
        { imgId: 39, payload: "recovering a diverted flight after a regional system outage", instruction: "The network system has been down for hours. You have a full cabin of tired passengers who need to get home. Fly a clean descent and keep your passengers happy by keeping the chatter to a minimum." },
        { imgId: 40, payload: "ferrying a corporate group to an annual summit", instruction: "Today you are flying a corporate group to an international tradeshow. Your passengers are excited to get to their destination and start networking or is that not working." },
        { imgId: 41, payload: "flying the airline's busiest regional route", instruction: "This is the busiest regional feeder in the network. Get the passengers on, fly the route, get to the gate, turnaround and repeat. You have a busy day ahead of you captain." },
        { imgId: 42, payload: "flying a scheduled hub feeder sector", instruction: "You have ordinary hub feeder route today. Ask ATC nicely for any shortcuts they can give you, so you can shut down and get out of the airport to that party you were invited to. Time off work is a wonderful thing." },
        { imgId: 43, payload: "flying a group of exchange students to their host country", instruction: "Excited exchange students are on their way to their host families. Keep it smooth, keep it punctual and no dad jokes please." },
        { imgId: 44, payload: "moving company staff to a seminar", instruction: "Company staff need transporting to a seminar after a recent merger. It is a full-cabin and a short sector. Let's hope everyone gets to keep their jobs this time." }
    ],
	executive: [
        { imgId: 45, payload: "flying {name} on a private schedule", instruction: "{name} wants the cabin quiet the whole way. Fly a smooth climb, a smooth descent and don't spill the champagne with steep turns.", weight: 15, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED, allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 46, payload: "taking {athlete} to an upcoming fixture", instruction: "{athlete} is on board, and you have been booked to fly them to their next event. Fly smoothly so {athlete} can rest during the flight.", weight: 15, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 47, payload: "flying executives to a negotiation", instruction: "Executives are working a deal in the back. Give them a soft ride and no drama on the way to the negotiation. If you're feeling naughty, you could use FLC during climb.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 48, payload: "flying a board to an offsite", instruction: "Your cabin is an office today. The laptops are out and the chatter is constant. Keep the coffee running and fly a smooth descent.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 49, payload: "flying state representatives", instruction: "State representatives are on the manifest today. Fly by the book and keep it professional. You are a professional, aren't you?", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 50, payload: "flying a {vip_type} to a high-level conference", instruction: "A {vip_type} is aboard bound for a high-level conference. Keep the control inputs gentle and the cabin environment comfortable. And don't forget the red carpet!", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 51, payload: "shuttling executives to a regional facility", instruction: "You have executives with a tight ground schedule waiting to board. Get them to their destination early if you can. These people keep our company in the air, so treat them well.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 52, payload: "flying a premium share owner", instruction: "A premium share owner used to the best is aboard today's flight. Make the whole piloting thing look effortless and go as fast as you can, I heard they like big numbers.", allowedClasses: ["BIZ JET", "TURBO", "HELI"], weight: 3 },
        { imgId: 53, payload: "flying prospective investors", instruction: "Prospective investors are being sold a company inside your cabin today. Keep the flight butter-smooth and keep the champagne on ice. This one is important to our client.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 54, payload: "moving a secure witness", instruction: "Local forces need a state witness transported. Fly A to B, no fuss and don't attract attention. Park at the FBO after landing and stay away from the main terminal.", allowedAircraft: ["C208", "STAR", "M600", "TBM8", "B60T", "BE20", "PC12", "H145", "H14M"], allowedClasses: ["BIZ JET"], weight: 3 },
        { imgId: 55, payload: "ferrying a Renaissance masterpiece to a private buyer", instruction: "A Renaissance masterpiece worth more than the jet is secured to one of the seats in the cabin, which is rather strange. Keep cabin temperature chilled, and stay clear of convective weather. The world needs more art and today you are the messenger.", weight: 1, allowedClasses: ["BIZ JET", "TURBO", "HELI"], excludedAircraft: SMALL_GA_TRAINERS },
        { imgId: 56, payload: "rushing legal executives to an industrial incident", instruction: "A PR mess is brewing and the legal team need to work on their case during today's flight. Shorten the route wherever you can and bring these legal professionals to their destination.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 57, payload: "flying a tech mogul's purebred cat", instruction: "A tech billionaire's fabulous feline has claimed the cabin. Keep the fish flowing, the banks shallow and the landing soft. This passenger expects the very best service on her way home.", weight: 1, allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 58, payload: "chartering a high-profile music icon", instruction: "{musician} wants to go shopping. Keep the champagne in the glass and turn a blind eye to any shenanigans above the clouds. What happens in the cabin, stays in the cabin. Remember that if you want to keep your job.", weight: 12, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 59, payload: "flying an owner to a holiday retreat", instruction: "The owner of this aircraft is loading their golf clubs in the back and has asked especially for you as their pilot. It must be your sparkling personality. Enjoy the scenic approach and keep the landing soft.", allowedClasses: ["BIZ JET"] },
        { imgId: 60, payload: "flying a short-hop business commute", instruction: "Today's passengers are skipping the airline queues. Ask for directs where ATC allows and shorten your block time where you can.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 61, payload: "flying {musician} to their next stadium gig", instruction: "{musician} and their management team need sleep before the show. Climb above the weather, dodge the bumps and keep cabin pressure steady. No alcohol on today's flight by order of the management.", weight: 12, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 62, payload: "flying {name} to meet a spiritual guru", instruction: "{name} is meeting a spiritual guru, and the press is watching this tail number. Park somewhere quiet and keep any mention of your passenger off open channels.", weight: 15, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED, excludedAircraft: SMALL_GA_TRAINERS },
        { imgId: 63, payload: "flying {athlete} to a championship fixture", instruction: "{athlete} needs to arrive rested and on time for the championship event. Ask for priority clearance and keep the ride smooth.", weight: 15, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 64, payload: "flying {name} to a film premiere", instruction: "{name} needs a discreet ride to a film premiere. Avoid the paparazzi hanging around the apron. Keep comms to a minimum, fly a clean approach and park quickly at the FBO.", weight: 15, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 65, payload: "flying {team} executives to an away fixture", instruction: "{team} executives are on board for an away fixture and the media are watching. Keep it professional, you are a professional aren't you? and don't forget to smile and be polite. These people keep our company in the air!", weight: 12, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 66, payload: "rushing a surgical team to a regional hospital", instruction: "The surgical team are ready to board the aircraft, and the hospital is waiting for them to arrive. Don't waste time and bring this team to the destination as quickly as you can.", allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 67, payload: "flying a VIP to an exclusive private gala", instruction: "This VIP charter has a bar stocked for comfort and fun. Make the landing butter-smooth so the passenger arrives in a good mood and ignore any guffawing coming from the cabin.", weight: 15, preferredAircraft: CELEBRITY_BIZ_JET_PREFERRED },
        { imgId: 68, payload: "rushing a tech CEO to a hostile board meeting", instruction: "His stock is in free-fall and the CEO needs to get back to his offices as quickly as possible to save the day. Expedite your checklists and do not forget the fuel.", allowedClasses: ["BIZ JET", "TURBO", "HELI"], excludedAircraft: ["UH1", "H14M", "H65M"] },
    ],
	medical: [
        { imgId: 69, payload: "airlifting a patient", instruction: "The patient is stable, but rough air will not help their condition. Watch the weather radar and keep the ride smooth all the way in. The medical team are already on board and expecting the patient soon." },
        { imgId: 70, payload: "transporting tissue for surgery", instruction: "Lifeguard priority! You are carrying essential medial tissue for a transplant. Ask ATC for priority on the way in. Helicopters go to the hospital; everyone else meets the ground crew on arrival." },
        { imgId: 71, payload: "airlifting a patient from a rural strip", instruction: "You may be heading into an uncontrolled field for this patient pickup. Check the runway before you commit to the approach." }
    ],
	lightFreight: [
        { imgId: 72, payload: "moving classified diplomatic files", instruction: "Classified diplomatic files are on board chained to someone who looks like John Cena. It can't be him, can it? Don't stop for anyone unless you want to be thrown off your own plane.", minCargoLoadFactor: 0.40 },
        { imgId: 73, payload: "delivering prototype processing units", instruction: "You are carrying prototype hardware that is sensitive to static and temperature. Check your environmental controls before taxi and departure. If this arrives damaged, you can look for a new job in the morning.", minCargoLoadFactor: 0.60 },
        { imgId: 74, payload: "moving a protected animal species", instruction: "Today we have live cargo riding in the back. No, not passengers, animals! Keep the banks shallow and go easy on the thrust unless you want to re-enact The Lion King at FL200.", minCargoLoadFactor: 0.60 },
        { imgId: 75, payload: "delivering fragile conservation saplings", instruction: "You are transporting living plants that are sensitive to pressure and temperature. Watch the descent rate on the way in and keep the cabin temps tropical.", minCargoLoadFactor: 0.40 },
        { imgId: 76, payload: "flying primary digital master drives", instruction: "Unedited production footage is in the hold, and the editing suite is waiting. It's up to you to deliver the digital masters on time. We've been told a representative from Marvel will meet you at the FBO. Please let it be Deadpool.", minCargoLoadFactor: 0.40 },
        { imgId: 77, payload: "relocating fragile historical manuscripts", instruction: "Climate-controlled manuscript cases have been packed into the hold. Have ground handling ready the moment you block in, these manuscripts are irreplaceable and sensitive to temperature and moisture. Keep the cabin cool and dry.", minCargoLoadFactor: 0.60 },
        { imgId: 78, payload: "rushing a critical AOG component", instruction: "Another aircraft has been grounded and it waiting on this part. Shorten the route where possible and fly a smooth approach.", minCargoLoadFactor: 0.60 },
        { imgId: 79, payload: "expediting priority medical freight", instruction: "This temperature controlled medical cargo is headed to a regional hospital. Ask ATC for priority and keep pressurization steady.", minCargoLoadFactor: 0.40 },
        { imgId: 80, payload: "transporting {med_cargo}", instruction: "{med_cargo} is in the hold. Keep cabin temperatures locked in and avoid fast climbs or descents that spike the pressure.", minCargoLoadFactor: 0.40 },
        { imgId: 81, payload: "expediting {med_cargo}", instruction: "A clinic needs this {med_cargo} for a procedure today. Keep the block as short as you can. There will be someone waiting to meet you when you park at the FBO.", minCargoLoadFactor: 0.40 },
        { imgId: 82, payload: "hauling farm produce from a rural strip", instruction: "Fresh produce from the field to the hold to the shops. Get airborne while it is still cold and dry and keep an eye on cabin temps. The cabin smells amazing today.", minCargoLoadFactor: 0.60 },
        { imgId: 83, payload: "moving regional express packages overnight", instruction: "Tonight's freight run keeps the regional network moving. Hit the slots to keep things running smoothly.", excludedAircraft: MAINLINE_JET_FREIGHTERS, minCargoLoadFactor: 0.60 },
        { imgId: 84, payload: "delivering regional post parcels", instruction: "You have an old-school mail run tonight. Weight is tight at every stop so do not hang about, you have more drops before sunset.", allowedAircraft: ["C20F", "C208", "KODF", "PC1F"], minCargoLoadFactor: 0.60 },
        { imgId: 85, payload: "delivering essential supplies to customers", instruction: "Supplies and mail are in the hold. Recheck density altitude before committing to the departure.", minCargoLoadFactor: 0.40 },
        { imgId: 86, payload: "delivering regional supplies", instruction: "A regional supply run is on the board today. Work the landing numbers for your arrival weight and use reverse if the runway is short.", excludedAircraft: ["B72F"], minCargoLoadFactor: 0.40 },
        { imgId: 87, payload: "shuttling regional lab samples and {med_cargo}", instruction: "These {med_cargo} need to get to their destination in one piece and quickly. You have been tasked with flying these essential items to their destination. Staff from the hospital will meet you on the apron. There is no time to explain, get there now!", minCargoLoadFactor: 0.40 },
        { imgId: 88, payload: "distributing the morning broadsheets", instruction: "It is 4 AM, the coffee is weak and your hold is full of today's news. Get the papers to the distributors before breakfast.", minCargoLoadFactor: 0.60 },
        { imgId: 89, payload: "rushing iced premium seafood to inland markets", instruction: "The ice is already melting on this catch. Get it to the restaurants before the dinner rush and keep the cabin cold. You don't need lobsters on the loose in the cabin (again).", minCargoLoadFactor: 0.60 },
        { imgId: 91, payload: "rushing a rare component to a stranded client", instruction: "A wealthy client's vintage car is stuck waiting on this part. Push to save time where you can, but keep the gauges in the green.", minCargoLoadFactor: 0.60 },
        { imgId: 92, payload: "ferrying critical machinery parts to a regional facility", instruction: "Harvest season is underway and an essential machine is down on the field. Get these parts there as fast as you safely can.", minCargoLoadFactor: 0.60 },
        { imgId: 94, payload: "connecting rural farm strips with mail and supplies", instruction: "Last flight before the sun goes down and it's up to you to bring the regional mail to the hub for distribution to rural areas. Fly a clean pattern and butter that landing. Who knows what condition the runway is in!", minCargoLoadFactor: 0.60 },
        { imgId: 95, payload: "delivering supplies to a community", instruction: "Food, fuel and mail are bound for a place with no road in. Check landing performance for your destination and watch for birds on approach.", allowedAircraft: ["C20F", "C208", "KODF", "PC1F"], minCargoLoadFactor: 0.60 },
        { imgId: 145, payload: "delivering urgent freight to a private airstrip", instruction: "A rural estate needs materials now and it is a short strip. Watch the crosswind on final and get the freight down cleanly.", minCargoLoadFactor: 0.50 }
    ],
    regionalFreight: [
        { imgId: 96, payload: "moving regional express packages overnight", instruction: "The regional night express depends on its slots. Hit them so the network does not stall.", excludedAircraft: MAINLINE_JET_FREIGHTERS, preferredAircraft: REGIONAL_JET_FREIGHTERS },
        { imgId: 97, payload: "moving priority overnight parcels", instruction: "The sort facility is on the clock. Ask for directs if there are any delays getting in the air.", preferredAircraft: REGIONAL_JET_FREIGHTERS },
        { imgId: 98, payload: "flying an overnight regional freight sector", instruction: "This red-eye clears the regional hubs. Stick to the ATC slots and keep the descent clean while the skies are quiet.", preferredAircraft: REGIONAL_JET_FREIGHTERS },
        { imgId: 99, payload: "expediting priority medical freight", instruction: "Temp-controlled medical cargo is headed to a regional hospital, and you are the quickest link. Ask ATC for priority." },
        { imgId: 100, payload: "shuttling regional lab samples and {med_cargo}", instruction: "{med_cargo} is going direct, skipping the hubs. The lab teams are waiting, so do not waste time on the ground." },
        { imgId: 101, payload: "ferrying critical machinery parts to a regional facility", instruction: "You are collecting machine parts for regional farmers today. Say the word and the teams will secure the loads in the hold. Expect a sluggish climb with so much weight on board." },
        { imgId: 102, payload: "delivering regional supplies", instruction: "This supply run will restock regional businesses. Work the landing numbers for your arrival weight and use reverse if the runway is short.", excludedAircraft: ["B72F"], preferredAircraft: REGIONAL_JET_FREIGHTERS },
        { imgId: 103, payload: "flying a late-evening regional freight sector", instruction: "A late night red-eye for a quiet regional network. Traffic is thin; fly efficiently and keep the chain moving through the night.", preferredAircraft: REGIONAL_JET_FREIGHTERS }
    ],
	heavyFreight: [
        { imgId: 104, payload: "delivering palletized nutrition and water packs", instruction: "Local supply chains are broken and relief pallets are on board. Ask for vectors where you can and get the supplies on the ground where they are needed most.", minCargoLoadFactor: 0.70 },
        { imgId: 105, payload: "delivering retail warehouse garment supplies", instruction: "Pallets of boxed clothing bound for warehouses is in the hold. Keep it clean and dry all the way down.", excludedAircraft: MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT, minCargoLoadFactor: 0.70 },
        { imgId: 106, payload: "moving authenticated historical artifacts", instruction: "Fragile museum pieces need to be delivered for a new exhibition. Descend with care, go easy on the brakes and no loops today.", weight: 3, excludedAircraft: MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT, minCargoLoadFactor: 0.50 },
        { imgId: 107, payload: "moving {cargo_type}", instruction: "Engineers are expecting this delivery of {cargo_type}. Stick to the block times and get it to the destination. Work has been suspended until you deliver these goods. Don't make them wait.", excludedAircraft: ["DC6A"].concat(MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT), minCargoLoadFactor: 0.70 },
        { imgId: 108, payload: "delivering luxury vehicles and parts", instruction: "High-value, luxury vehicles have been secured to the main deck. Make sure the loadmaster checks every strap before the door closes and no, you can't sit in them.", excludedAircraft: ["B461_MIL", "B462_MIL", "DC6A"].concat(MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT), minCargoLoadFactor: 0.50 },
        { imgId: 109, payload: "loading a high-value luxury sports car", instruction: "A bespoke supercar has been loaded for delivery. Go easy on the controls and confirm the straps are secure before closing up. Do not touch the car. Do not get in the car. Do not breathe on the car.", weight: 3, excludedAircraft: ["B461_MIL", "B462_MIL", "DC6A"].concat(MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT), minCargoLoadFactor: 0.50 },
        { imgId: 110, payload: "ferrying {cargo_type} and heavy oilfield equipment", instruction: "{cargo_type} and heavy oilfield equipment are bolted to the floor rails. Expect a slower flight; watch the fuel and stay ahead of the power curve on final. We don't want you dropping out of the sky just before you land. Yes, we all remember when that happened.", minCargoLoadFactor: 0.70 },
        { imgId: 111, payload: "returning a decommissioned avionics bay", instruction: "A retired avionics bay has been requested by a team at your destination airport. Check the tie-downs before you roll and no steep turns on this one.", minCargoLoadFactor: 0.50 },
        { imgId: 112, payload: "transporting premium edible goods for wholesale", instruction: "The supermarkets are waiting for this delivery. Keep the temperature steady so nothing spoils. You do want to get paid, don't you?", excludedAircraft: MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT, minCargoLoadFactor: 0.70 },
        { imgId: 113, payload: "transporting bulk commercial perishables", instruction: "This is a delivery of high end consumer electronics straight from the factory. Watch the V-speeds on the takeoff roll and keep the cabin temperature in check.", excludedAircraft: MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT, minCargoLoadFactor: 0.70 },
        { imgId: 114, payload: "moving priority overnight parcels", instruction: "The sort facility is on the clock. Ask for directs if you experience any delays getting in the air.", excludedAircraft: MIL_AIRLIFTER_EXCLUDED_OVERNIGHT_PARCELS.concat(REGIONAL_JET_FREIGHTERS), minCargoLoadFactor: 0.70 },
        { imgId: 115, payload: "transporting heavy secure bullion", instruction: "A central-bank transfer of gold bullion needs transporting and there are lots of frowning people dressed in black waiting on the ramp. The ground team will handle loading and offload. Expect an armed team on board for this job.", weight: 3, minCargoLoadFactor: 0.85 },
        { imgId: 116, payload: "moving an oversized, max-payload cargo manifest", instruction: "The aircraft has been loaded to almost MTOW. Expect a long roll and a lazy climb; double-check the V-speeds before committing and keep the power on.", excludedAircraft: ["DC6A"], minCargoLoadFactor: 0.85 },
        { imgId: 117, payload: "flying an overnight route", instruction: "This red-eye clears the big sorting hubs. Hit the ATC slots and manage the heavy descent while the sky is quiet.", preferredAircraft: REGIONAL_JET_FREIGHTERS, excludedAircraft: MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT, minCargoLoadFactor: 0.70 },
        { imgId: 118, payload: "moving an absolute mountain of impulse buys", instruction: "The sort facility is backed up and the hold is stuffed to the roof. Expect a slow rotate and a step-climb if the air is warm tonight.", excludedAircraft: MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT, minCargoLoadFactor: 0.70 },
        { imgId: 119, payload: "transporting Formula racing chassis and paddock gear", instruction: "High-value, time-critical Formula One chassis needs transporting for a race. You cannot afford to make a mistake with this one. These cars cost upwards of $15 million, so take it easy.", weight: 3, excludedAircraft: ["DC6A", "B461_MIL", "B462_MIL"].concat(MIL_AIRLIFTER_EXCLUDED_HEAVY_FREIGHT), minCargoLoadFactor: 0.50 },
        { imgId: 120, payload: "loading heavy industrial machinery", instruction: "The loadmaster is still chaining the oversized plant kit to the main deck. Confirm tie-downs and floor limits before you call for pushback and check fuel before you leave.", excludedAircraft: ["DC6A"], minCargoLoadFactor: 0.85 },
        { imgId: 121, payload: "loading a heavy industrial generator", instruction: "The ground crew are locking down an oversized generator on the deck. Check floor limits, chains and CG before pushback.", excludedAircraft: ["DC6A"], minCargoLoadFactor: 0.50 },
        { imgId: 122, payload: "transporting a replacement engine turbine module", instruction: "You have a fragile fan module on board for an AOG recovery. Keep the ride smooth and the hold temp steady.", minCargoLoadFactor: 0.50 },
        { imgId: 123, payload: "transporting server racks and data-centre hardware", instruction: "You have server racks and data-centre hardware in the hold. Fly smooth, keep cabin temp in spec and do not ask what runs on these machines.", minCargoLoadFactor: 0.70 }
    ],
    surveyServices: [
        { imgId: 124, payload: "distributing localized civic awareness materials", instruction: "You are flying the assigned grid so the civic leaflet drop covers the sector evenly. Stay on the planned track." },
        { imgId: 125, payload: "surveying local power and pipeline grids", instruction: "You are surveying the power and pipeline grid today. Stay within the inspection corridor and keep a sterile cockpit while you are on the line." },
        { imgId: 126, payload: "inspecting crop yields", instruction: "You are low and slow over the fields today. Watch for unmarked power lines and keep the track steady for the survey team." },
        { imgId: 127, payload: "mapping a municipal expansion zone", instruction: "You are mapping a municipal expansion zone. Hold a steady track along the route so the survey team gets clean readings." },
        { imgId: 128, payload: "mapping subsurface anomalies", instruction: "You are mapping subsurface anomalies today. Hold constant airspeed and altitude — the magnetometer hates wandering." },
        { imgId: 129, payload: "flying insurance assessment teams", instruction: "A storm tore through here yesterday. Hold the profile over the damage so the insurance assessors can scan from above." },
        { imgId: 130, payload: "flying LIDAR equipment over suspected ancient ruins", instruction: "Researchers want LIDAR passes over suspected ruins below. Hold altitude and track tight across the grid so the survey team gets clean coverage." },
        { imgId: 131, payload: "flying a photographer for a high-end property portfolio", instruction: "You have a photographer on board who needs clean, stable orbits over a few waypoints. Work with the photographer and keep the airframe smooth.", excludedAircraft: ["U16"] },
        { imgId: 132, payload: "flying researchers over a {sci_fi}", instruction: "Researchers want you over a {sci_fi} on this route. Map it from above and try to ignore the weird static chewing through the radios.", weight: 3 },
        { imgId: 133, payload: "assisting authorities in a visual search for a missing vehicle", instruction: "You are assisting a visual search for a missing vehicle. Fly low over the last known coordinates and keep your eyes outside for anything that looks like a signal.", weight: 3, excludedAircraft: ["BE60", "STAR"] },
    ],
    lightPax: [
        { imgId: 90, payload: "relocating the airframe to a certified avionics shop", instruction: "The owner of this aircraft says that the GPS is acting up and has asked you to bring it to the nearest service center. Fly carefully and keep your eyes outside if the GPS turns off unexpectedly." },
        { imgId: 93, payload: "delivering a recently purchased airframe", instruction: "The broker just handed over the keys. This is your new aircraft, congratulations. Fly her home, watch the temperatures and don't push her too hard on your first flight." },
        { imgId: 134, payload: "moving industrial staff between sites", instruction: "You have an ordinary staff shuttle today. Nothing fancy — get the passengers there on time." },
        { imgId: 135, payload: "conducting a standardization flight", instruction: "You are conducting a standardization flight in the local pattern. Standard maneuvers and clean radio work.", weight: 3 },
        { imgId: 136, payload: "shuttling an independent engineering consultant", instruction: "You have an engineering consultant working paperwork in the back. Find smooth air and keep the inputs gentle." },
        { imgId: 137, payload: "keeping a community linked by light aircraft", instruction: "This town relies on your connection. Stick to the schedule — plenty of passengers have onward flights at the hub." },
        { imgId: 138, payload: "flying {name} on a private schedule", instruction: "{name} wants quiet and discretion on this run. Smooth climb, smooth descent and keep the ride soft.", weight: 12, allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 139, payload: "flying {name} to meet a spiritual guru", instruction: "You are flying {name} to meet a spiritual guru and the press is watching this flight. Park away from the main building and keep {name} off open channels.", weight: 12, excludedAircraft: SMALL_GA_TRAINERS, allowedClasses: ["BIZ JET", "TURBO", "HELI"] },
        { imgId: 140, payload: "flying a romantic scenic twilight flight", instruction: "You have a romantic twilight scenic on the books tonight. Smooth RPM, shallow banks and a gentle profile — do not spoil the moment.", weight: 1 },
        { imgId: 141, payload: "rushing a stranded businessman to a regional hub", instruction: "You have a stranded businessman who missed the airline connection and grabbed your last seat. Can you save the day and get him to the hub on time?", weight: 2 },
        { imgId: 142, payload: "bringing passengers home to their families", instruction: "You are the only link between these towns today. Plan the fuel, watch the approach winds and butter that landing." },
        { imgId: 143, payload: "flying a honeymooning couple to a remote retreat", instruction: "You have a honeymooning couple on a chartered getaway. Gentle turns, smooth air and a soft landing — match the holiday mood.", weight: 1 },
        { imgId: 144, payload: "flying a regional medical examiner to an incident site", instruction: "You have a regional medical examiner on a time-sensitive call-out. Get to the incident site as fast as you safely can and check the runway before you commit.", weight: 3 },
        { imgId: 146, payload: "repositioning an aircraft for its new owner", instruction: "The deal is done and the keys are handed over. Ferry her to the new home base, watch the temps — unfamiliar airframe today." }
    ],
    highAltServices: [
        { imgId: 147, payload: "gathering specific meteorological data", instruction: "You are gathering meteorological data for the science team. Fly the altitudes and headings they ask for — the readings only count if you nail the profile." },
        { imgId: 148, payload: "flying atmospheric researchers to a developing system", instruction: "You have atmospheric researchers who need to drop sensors ahead of a major pressure shift. Get close enough to observe, but stay clear of the convective cells." }
    ],
    vintageOps: [
        { imgId: 149, payload: "flying a historic airshow demonstration", instruction: "You are flying a historic airshow demonstration today. Static display on the ground, then a short aerial routine — check the fluids before you roll.", allowedClasses: ["WARBIRD", "JET"], excludedAircraft: ["DC6A"], weight: 3 },
        { imgId: 150, payload: "positioning for a closed-course handicap race", instruction: "You are positioning for a closed-course handicap race. Visual transit to the staging field and keep the airframe clean and trimmed.", excludedAircraft: ["U16", "DC6A", "DC6B", "V10", "P38"] },
        { imgId: 151, payload: "ferrying a vintage airframe to an aviation museum", instruction: "You are ferrying a vintage airframe to the museum. Treat her gently, stay well inside the structural limits — she is old and the museum wants her in one piece." },
        { imgId: 152, payload: "acting as a chase plane for a historic squadron", instruction: "You are chase plane for a historic squadron today. Hold your spacing, stay aware and watch the temps — formation power settings can run hot.", allowedClasses: ["GA"] },
        { imgId: 153, payload: "flying a commemorative low-level transit", instruction: "You are flying a commemorative low-level transit. Hit time-on-target over the memorial clean and keep it respectful." },
        { imgId: 154, payload: "keeping current in a historic airframe", instruction: "You are keeping current in a historic airframe. Local pattern work so you and the aircraft stay approved for the next public display." },
        { imgId: 155, payload: "delivering a newly restored airframe to a preservation trust", instruction: "You are delivering a newly restored airframe to the preservation trust. She is irreplaceable — watch the gauges, dodge convective weather and deliver her clean to the museum ramp." },
        { imgId: 156, payload: "ferrying to a regional aviation festival", instruction: "You need to be on the staging grounds before sunset. Cruise power conservative to spare the engine — expect a crowd watching your arrival." },
        { imgId: 157, payload: "flying a chartered remembrance flight", instruction: "You are flying a chartered remembrance flight in memory of those who flew this airframe before you. Keep the maneuvers gentle and the fluids in the green.", weight: 3 }
    ],
	// DC-6A freight exclusive
    vintageProplinerFreight: [
        { imgId: 158, payload: "hauling oversized vintage freight", instruction: "You have a classic load for a classic bird. Keep the RPMs synced, mind the cowl flaps and plan your descent early — no speedbrakes on this one." },
        { imgId: 159, payload: "flying live agricultural freight", instruction: "The hold smells terrible, but the payout is good. Easy on the bank angles and grease the landing." },
        { imgId: 160, payload: "moving heavy goods in a vintage airframe", instruction: "You are moving heavy goods in a vintage airframe today. Watch the engine temps, work the flight engineer panel and expect the controls to feel a bit slow.", allowedAircraft: ["DC6A"] },
        { imgId: 161, payload: "loading palletized commercial freight", instruction: "The warehouse teams are still building the pallets. Hit your departure slot or the whole sort window slips.", preferredAircraft: ["DC6A"] }
    ],
	// DC-6B PAX Exclusive
    vintageAirliner: [
        { imgId: 162, payload: "flying a premium overnight cross-country", instruction: "You have a premium overnight cross-country with half the cabin asleep. Keep the pitch smooth and the step-climb easy so the passengers stay that way.", allowedAircraft: ["DC6B"], excludedAircraft: ["DC6A"] },
        { imgId: 163, payload: "flying holidaymakers across the country", instruction: "You have holidaymakers across the country today. Watch the cylinder head temps on the ground and get the cowl flaps sorted early before you pick through any local weather.", allowedAircraft: ["DC6B"], excludedAircraft: ["DC6A"] },
        { imgId: 164, payload: "flying a full load of {industry} executives and engineers to the extraction sites", instruction: "You have a full load of {industry} executives and engineers for the extraction sites. Have the flight engineer keep cross-feeds tidy so the centre of gravity stays balanced.", allowedAircraft: ["DC6B"], excludedAircraft: ["DC6A"] },
        { imgId: 165, payload: "flying sports fans to the match", instruction: "You have sports fans heading to the match. Check carb heat and the de-icing boots before you enter the terminal area.", allowedAircraft: ["DC6B"], excludedAircraft: ["DC6A"] },
        { imgId: 166, payload: "flying an iconic passenger shuttle", instruction: "You are on an iconic passenger shuttle today. Expect a lazy climb off the runway — mind the power recovery and do not thrash the engines.", allowedAircraft: ["DC6B"], excludedAircraft: ["DC6A"] }
    ],
    'helicopterOps-CIV': [
        { imgId: 167, payload: "flying a local scenic hop", instruction: "You have passengers on a local scenic hop today. Take them around the landmarks on a visual pattern, then set down at the destination and keep clear of the GA traffic." },
        { imgId: 168, payload: "holding steady for a survey photographer", instruction: "You are holding steady for a survey photographer. Work with the photographer and give clean orbits over the waypoints — smooth is everything." },
        { imgId: 169, payload: "watching the local transit corridors", instruction: "You are watching the local transit corridors from above. Hold over the big interchanges so the spotter can call traffic conditions — easy turns, predictable track." },
        { imgId: 170, payload: "flying a short on-demand charter", instruction: "You have a client who wants to skip the gridlock. Direct routing if you can get it and do not hang about." },
        { imgId: 171, payload: "extracting a trauma victim from a major roadway", instruction: "First responders have a landing zone ready on the roadway. Get in, get the patient aboard and go — the clock is running." },
        { imgId: 172, payload: "searching for a stranded group of travellers", instruction: "You are searching for a stranded group of travellers. Work patterns over the last known coordinates and be ready to hoist if you cannot put down." },
        { imgId: 173, payload: "providing aerial overwatch", instruction: "You are providing aerial overwatch for ground units. Talk to the ground team, hold a safe height over the target area and stay predictable." },
        { imgId: 174, payload: "mapping a new property development", instruction: "You are mapping a new property development. Fly precise tracks across the survey grid so the cameras get clean, overlapping coverage." },
        { imgId: 175, payload: "positioning industrial equipment", instruction: "You are positioning industrial equipment with a precision hover. Watch torque and engine limits the whole time you are hanging there." },
        { imgId: 176, payload: "locating tagged animal populations", instruction: "You are locating tagged animal populations for the biologists. Keep visual contact while the telemetry is logged and do not spook the wildlife if you can help it." },
        { imgId: 177, payload: "shuttling an executive from the airport", instruction: "You have an executive hop from the FBO to the helipad. Smooth transition, soft set-down and no drama." },
        { imgId: 178, payload: "covering a civic event live", instruction: "You are covering a civic event live from the air. Set up a loiter clear of other traffic and keep your movements predictable for the camera operator." },
        { imgId: 179, payload: "capturing dynamic tracking shots", instruction: "You are capturing dynamic tracking shots today. Work with the ground director, match the subject's pace and keep the follow smooth with no sudden inputs." },
        { imgId: 180, payload: "moving heavy pipe segments into rugged terrain", instruction: "You have external load work moving heavy pipe segments into rugged terrain. Watch torque and rotor RPM while you ease the segments into place.", minCargo: 201 },
        { imgId: 181, payload: "cleaning high-tension wire infrastructure", instruction: "You are cleaning high-tension lines today. Fly low and slow so the boom operator can hit the insulators. Mind the wind — you do not want to drift into the wires." },
        { imgId: 182, payload: "transporting highly sensitive legal tenders", instruction: "You have highly sensitive legal tenders on board and the case is handcuffed to the courier. Fly straight and be ready for an engine-running offload the moment you arrive." },
        { imgId: 183, payload: "airlifting an unidentifiable metallic pillar", instruction: "Hikers found a smooth, heavy metal pillar in a slot canyon. Ground crews say the air goes cold near it and your compass will not settle.", minCargo: 201, weight: 3 },
    ],
	// MILITARY
	'heavyFreight-MIL': [
        { imgId: 184, payload: "moving dense tactical vehicle components", instruction: "You have a heavy tactical load today. Double-check the CG on the loadsheet before you start the engines.", minCargoLoadFactor: 0.80 },
        { imgId: 185, payload: "relocating modular defense components", instruction: "The depot needs this kit for assembly the moment you land. Stick to the filed plan and hit the block.", minCargoLoadFactor: 0.80 },
        { imgId: 186, payload: "moving sensitive industrial hardware", instruction: "You have sealed manifests and no questions on this run. Head straight for the remote ramp when you arrive.", minCargoLoadFactor: 0.50 },
        { imgId: 187, payload: "ferrying urgent technical spares to a regional depot", instruction: "You have a priority load on board. Get it there on time or the maintenance schedule slips.", minCargoLoadFactor: 0.50 },
        { imgId: 188, payload: "transporting AOG parts for a fleet-wide inspection", instruction: "Maintenance are standing by for this hardware. Do not waste a minute on the way in.", minCargoLoadFactor: 0.80 },
        { imgId: 189, payload: "loading tactical cargo pallets", instruction: "You have palletized military stores going on the main deck. Check tie-down tension and CG before you start engines.", allowedAircraft: ["C160"], minCargoLoadFactor: 0.50 },
        { imgId: 190, payload: "delivering refugee relief supply pallets", instruction: "You have humanitarian pallets bound for a forward distribution point. Keep the schedule and make sure the offload teams are ready when you land.", allowedAircraft: ["C160", "A400"], minCargoLoadFactor: 0.80 }
    ],
    'helicopterOps-MIL': [
        { imgId: 191, payload: "deploying a specialized ground team", instruction: "You are deploying a specialized ground team into the LZ. Use the terrain on the way in, stabilize the hover and get the team out clean.", heliOps: true },
        { imgId: 192, payload: "conducting a perimeter survey", instruction: "We have reports of suspicious movement along the vector. Hold corridor track, log contacts and watch loiter fuel. Do not engage.", heliOps: true },
        { imgId: 193, payload: "flying visiting dignitaries around the installation", instruction: "You have visiting dignitaries on board who want clear photos of the base from a safe standoff. Soft ride and predictable banks.", staffShuttle: true },
        { imgId: 194, payload: "conducting a local SAR training sortie", instruction: "You are outbound to the training grid for low-altitude hover work. Keep your eyes peeled for the training beacons.", heliOps: true },
        { imgId: 195, payload: "delivering essential provisions to an observation post", instruction: "You have field rations and spare radio batteries in the back. Ease into the LZ and watch for wind shear off the terrain.", heliOps: true },
        { imgId: 196, payload: "transporting regional commanders to a joint briefing", instruction: "You have regional commanders on board for a joint briefing. Comfortable transit, direct routing and no sightseeing — security wants you there with no detours.", staffShuttle: true },
        { imgId: 183, payload: "airlifting an unidentifiable metallic pillar", instruction: "Hikers found a smooth, heavy metal pillar in a slot canyon. Ground crews say the air goes cold near it and your compass will not settle.", minCargo: 201, weight: 3, heliOps: true }
    ],
    'militaryTransit-MIL': [
        { imgId: 197, payload: "transferring encrypted telemetry hardware", instruction: "You have secure flight data recorders from a defense contractor on board. Standard OPSEC — keep it quiet and stick to the plan." },
        { imgId: 198, payload: "moving unmarked secure containers", instruction: "You have unmarked secure containers on the flight plan. Talk normally on the radio, but go straight to destination." },
        { imgId: 199, payload: "relocating contracted defense personnel", instruction: "You have a standard military charter with contracted defense personnel on board. Hit the schedule and fly it like any heavy jet sector.", excludedAircraft: ["VULC"], requiresPax: true },
        { imgId: 200, payload: "repositioning to a strategic staging airfield", instruction: "You are on a peacetime repositioning to a strategic staging airfield. Sterile cockpit and work with military ATC for your arrival window." },
        { imgId: 201, payload: "executing a peacetime navigation exercise", instruction: "You are executing a peacetime navigation exercise. Nail the fuel plan and the waypoint timings — fly the exercise by the numbers." },
        { imgId: 202, payload: "relocating staff personnel under tactical escort", instruction: "You have a low-profile transit with staff personnel under escort. Direct routing, assigned levels and no deviations from the flightplan.", excludedAircraft: ["VULC"], requiresPax: true },
        { imgId: 203, payload: "delivering priority diplomatic communications", instruction: "You have priority diplomatic communications on board. Maintain chain of custody and do not leave the filed flightpath." },
        { imgId: 204, payload: "transferring cryogenic xenobiological tissue samples", instruction: "Captain, this flight officially does not exist. Ignore any knocking from the hold and do not log the sector.", weight: 1 },
        { imgId: 205, payload: "providing high-speed search and rescue support", instruction: "You are providing high-speed SAR support along the route. Scan for beacons or visual distress, pass coordinates to the extraction teams and hold your search profile." },
        { imgId: 206, payload: "patrolling the designated vector for surface anomalies", instruction: "You are patrolling the designated vector for surface anomalies. Keep eyes on the surface and call any unregistered traffic up to sector command." },
        { imgId: 207, payload: "providing a localized UHF/VHF relay for ground exercises", instruction: "You are holding steady over the sector as a UHF/VHF relay for ground exercises. Watch your fuel and monitor your instruments and oxygen." }
    ],
    'tacticalJet-MIL': [
        { imgId: 208, payload: "gathering passive telemetry data", instruction: "You are gathering passive telemetry data today. Fly the filed route exactly so the onboard equipment can triangulate regional signal traffic." },
        { imgId: 209, payload: "providing a target profile for ground-based early warning systems", instruction: "You are providing a target profile for ground early warning systems. Hold the altitude and airspeed in your flightplan so the stations can calibrate their radar returns." },
        { imgId: 210, payload: "intercepting unidentified radar contacts", instruction: "You are intercepting unidentified radar contacts. Keep speed up and watch the tactical displays for vectored intercepts." },
        { imgId: 211, payload: "conducting a cooperative cross-service nav exercise", instruction: "You are on a cooperative cross-service nav exercise. Match profiles with the allied assets — timing has to be spot-on for the rendezvous." },
        { imgId: 212, payload: "verifying long-range optical and radar sensor integrity", instruction: "Ground stations need a clean target for tracking telemetry. Keep the airframe smooth — the pods hate vibration." },
        { imgId: 213, payload: "re-validating primary approach vectors", instruction: "You are re-validating primary approach vectors today. Non-precision approach practice — log the navaids properly and fly it by the book." },
        { imgId: 214, payload: "repositioning airframes for off-cycle maintenance", instruction: "You are on a ferry flight for off-cycle maintenance. Watch your temps and keep the engines happy." },
        { imgId: 215, payload: "conducting a two-ship proficiency transit", instruction: "You are on a two-ship proficiency transit. Keep wingman separation inside the limits through climb and cruise — no surprises." },
        { imgId: 216, payload: "conducting a handling and proficiency check", instruction: "You are conducting a handling and proficiency check. Fly the filed route with sharp energy management and respect the floor altitudes in the simulated combat phase." },
        { imgId: 217, payload: "executing a high-speed, terrain-masking profile", instruction: "You are executing a terrain-masking profile today. Terrain-following or strict visual low-level — hold 250 feet AGL through the corridor and watch for birds." },
        { imgId: 218, payload: "providing support for regional exercises", instruction: "You are Red Air today. Fly the briefed intercept vectors, test friendly radar response, acknowledge sim contacts, then proceed to destination.", excludedAircraft: ["B461_MIL"] },
        { imgId: 219, payload: "ferrying to a regional aviation festival", instruction: "You have been instructed to be on the staging grounds before sunset. Cruise power to spare the engines — expect a crowd watching your arrival." },
        { imgId: 220, payload: "conducting aerial refuelling approach practice", instruction: "You are conducting aerial refuelling approach practice. Fly the assigned route and hold airspeed and altitude per your flightplan the whole way.", excludedAircraft: ["SPIT", "BF109", "F6F", "P38"] }
    ],
    'reconnaissance-MIL': [
        { imgId: 220, missionType: 32, payload: "conducting aerial refuelling approach practice", instruction: "You are conducting aerial refuelling approach practice. Fly the assigned route and hold airspeed and altitude per your flightplan the whole way.", allowedAircraft: STRATEGIC_RECON_AIRCRAFT, excludedAircraft: ["SPIT", "BF109", "F6F", "P38", "FW08", "A6M5"] },
        { imgId: 221, missionType: 32, payload: "conducting a transit reconnaissance sortie", instruction: "You are flying departure to destination on the assigned recon route. Hold altitude and airspeed so the sensors collect continuous imagery along the corridor.", allowedAircraft: STRATEGIC_RECON_AIRCRAFT },
        { imgId: 222, missionType: 32, payload: "mapping the assigned transit corridor", instruction: "You are mapping the assigned transit corridor today. Fly direct, hold a steady track and altitude and let the mapping systems build a clean picture.", allowedAircraft: STRATEGIC_RECON_AIRCRAFT, preferredAircraft: VULCAN_RECON_PREFERRED },
        { imgId: 223, missionType: 32, payload: "photographing designated areas along the route", instruction: "You are photographing designated areas along the route. Match the briefed headings and timings so analysts can sync the imagery to the mission clock.", allowedAircraft: STRATEGIC_RECON_AIRCRAFT, preferredAircraft: VULCAN_RECON_PREFERRED },
        { imgId: 249, missionType: 32, payload: "conducting a two-ship formation proficiency transit", instruction: "You are on a two-ship formation transit, departure to destination. Keep wingman spacing inside limits through the climb and cruise.", allowedAircraft: STRATEGIC_RECON_AIRCRAFT, preferredAircraft: VULCAN_RECON_PREFERRED },
        { imgId: 250, missionType: 32, payload: "conducting aerial refuelling approach practice", instruction: "You are conducting aerial refuelling approach practice. Hold airspeed and altitude as briefed and do not break another refuelling nozzle.", allowedAircraft: STRATEGIC_RECON_AIRCRAFT, excludedAircraft: ["SPIT", "BF109", "F6F", "FW08", "P38"] }
    ],
    gliderOps: [
        { imgId: 224, payload: "flying a club cross-country task between glider fields", instruction: "You will launch from {dep_field} and work lift toward {dest_field}. Read the sky — developing cumulus marks the thermals, with puffy tops and dark flat bases. Give decaying wispy cloud a wide berth. Stay VFR and arrive with height for a normal circuit." },
        { imgId: 225, isLocal: true, payload: "building local soaring currency above {dep_field}", instruction: "Stay in the local area above {dep_field}. Practice thermalling, position reports and clean circuit entries. Under developing cumulus, core the strongest lift. Recover to the glider strip when your block time expires." },
        { imgId: 226, payload: "working available lift toward {dest_field}", instruction: "You are working whatever lift the day offers between {dep_field} and {dest_field}. Use thermals under growing Cu, slope lift or cloud streets where you can. Stay clear of lee turbulence and do not press into sink without a landing option." },
        { imgId: 227, payload: "conducting a dual instructional sortie from {dep_field}", instruction: "You have a student aboard for handling and lookout practice. Demonstrate energy management and circuit work, and talk through how you read the sky as you fly. Keep the ride smooth and verbalize every decision." },
        { imgId: 228, payload: "ferrying under power from {dep_field} to {dest_field}", instruction: "The club needs this glider repositioned from {dep_field} to {dest_field}. Climb to a safe altitude, shut down to soar when you can and keep enough battery or fuel for a go-around reserve at destination." },
        { imgId: 229, payload: "flying a contest-style practice task", instruction: "You are flying a practice speed task from {dep_field} to {dest_field}. Work your height band, plan turns before weak lift and use cloud streets to cover ground. Progress by soaring technique, not minimum time under engine power." }
    ]
};

const names = ["Tom Cruise", "Dwayne Johnson", "Leonardo DiCaprio", "Scarlett Johansson", "Margot Robbie", "Zendaya", "Tom Holland", "Robert Downey Jr.", "Brad Pitt", "Angelina Jolie", "Will Smith", "Pedro Pascal", "Timothée Chalamet", "Florence Pugh", "Ryan Reynolds", "Hugh Jackman", "Chris Hemsworth", "Keanu Reeves", "Meryl Streep", "Jackie Chan"];
const athletes = ["Cristiano Ronaldo", "Lionel Messi", "LeBron James", "Stephen Curry", "Simone Biles", "Tiger Woods", "Lewis Hamilton", "Patrick Mahomes", "Shohei Ohtani", "Caitlin Clark", "Novak Djokovic", "Rafael Nadal", "Usain Bolt", "Kylian Mbappé", "Virat Kohli", "Serena Williams", "Michael Phelps", "Kevin Durant", "Carlos Alcaraz", "Katie Ledecky"];
const teams = ["Real Madrid", "Barcelona", "Manchester United", "Manchester City", "Bayern Munich", "Paris Saint-Germain", "Liverpool", "Los Angeles Lakers", "Golden State Warriors", "Boston Celtics", "New York Yankees", "Los Angeles Dodgers", "Kansas City Chiefs", "Dallas Cowboys", "San Francisco 49ers", "Ferrari", "Mercedes F1 Team", "Mumbai Indians", "All Blacks", "Toronto Maple Leafs"];
const musician = ["Taylor Swift", "Beyoncé", "Drake", "The Weeknd", "Billie Eilish", "Bad Bunny", "Ed Sheeran", "Adele", "Justin Bieber", "Bruno Mars", "Dua Lipa", "Rihanna", "Lady Gaga", "Chris Martin", "Eminem", "Harry Styles", "Olivia Rodrigo", "Post Malone", "Kendrick Lamar", "BTS"];
const medCargo = ["specialized surgical tools", "temperature-sensitive donor organs", "blood plasma reserves", "advanced diagnostic equipment", "rare antivenom vials", "experimental vaccine cultures"];
const industry = ["Tech", "Energy", "Finance", "Pharmaceutical", "Real Estate", "Automotive", "Aerospace", "Telecommunications"];
const vipType = ["global diplomat", "tech billionaire", "renowned film director", "royal family member", "high-profile whistleblower", "media tycoon"];
const sciFi = ["geometric anomaly", "unexplained localized magnetic distortion", "perfectly circular crop depression", "unidentified pulsating light source", "rapidly expanding sinkhole"];
const cargoType = ["lithium-ion batteries", "drilling equipment", "server racks", "luxury vehicle parts", "stage rigging", "humanitarian rations"];

const preFlightQuotes = [
{ text: "When once you have tasted flight, you will forever walk the earth with your eyes turned skyward, for there you have been, and there you will always long to return.", author: "Not Leonardo DaVinci" },
{ text: "Man must rise above the Earth, to the top of the atmosphere and beyond, for only thus will he fully understand the world in which he lives.", author: "paraphrase of a concept from Plato's Phaedo" },
{ text: "I fly because it releases my mind from the tyranny of petty things.", author: "Antoine de Saint-Exupery" },
{ text: "The desire to fly is an idea handed down to us by our ancestors who, in their grueling travels across trackless lands in prehistoric times, looked enviously on the birds soaring freely through space, at full speed, above all obstacles, on the infinite highway of the air.", author: "Wilbur Wright" },
{ text: "Sometimes, flying feels too God-like to be attained by man. Sometimes, the world from above seems too beautiful, too wonderful, too distant for human eyes to see.", author: "Charles A. Lindbergh" },
{ text: "Pilots are a rare kind of human. They leave the ordinary surface of the word, to purify their soul in the sky, and they come down to earth, only after receiving the communion of the infinite.", author: "Jose Maria Velasco Ibarra" },
{ text: "Airspeed, altitude, and brains. Two are always needed to successfully complete the flight.", author: null },
{ text: "Both optimists and pessimists contribute to our society. The optimist invents the airplane and the pessimist the parachute.", author: "Gil Stern" },
{ text: "If black boxes survive air crashes, why don’t they make the whole plane out of that stuff?", author: "George Carlin" },
{ text: "You’ve never been lost until you’ve been lost at Mach 3.", author: "Paul F. Crickmore" },
{ text: "Learn from the mistakes of others. You won’t live long enough to live all of them yourself.", author: null },
{ text: "You start with a bag full of luck and an empty bag of experience. The trick is to fill the bag of experience before you empty the bag of luck.", author: null },
{ text: "Good judgment comes from experience. Unfortunately, the experience usually comes from bad judgment.", author: null },
{ text: "There are old pilots and there are bold pilots. However, there are no old, bold pilots.", author: null },
{ text: "The engine is the heart of an airplane, but the pilot is its soul.", author: "Walter Raleigh" },
{ text: "Aviation is proof that given the will, we have the capacity to achieve the impossible.", author: "Eddie Rickenbacker" },
{ text: "Flying is more than a sport and more than a job; flying is pure passion and desire.", author: "General Adolf Galland" },
{ text: "The airplane stands for freedom, for joy, for the power to understand.", author: "Richard Bach" },
{ text: "We who fly do so for the love of flying.", author: "Cecil Day-Lewis" },
{ text: "Adventure is worthwhile in itself.", author: "Amelia Earhart" },
{ text: "Flying is hypnotic and all pilots are victims to the spell.", author: "Ernest K. Gann" },
{ text: "Life is like a landscape. You live in the midst of it but can describe it only from the vantage point of distance.", author: "Charles Lindbergh" },
{ text: "I owned the world that hour as I rode over it – free of the earth, free of the mountains, free of the clouds, but how inseparably I was bound to them.", author: "Charles Lindbergh" },
{ text: "Real freedom lies in wildness, not in civilization.", author: "Charles Lindbergh" },
{ text: "Flying is learning how to throw yourself at the ground and miss.", author: "Douglas Adams" }
];
if (typeof globalThis !== "undefined") {
    globalThis.SCENARIO_JOB_TITLES = SCENARIO_JOB_TITLES;
    globalThis.missionMatrix = missionMatrix;
    globalThis.scenarioDB = scenarioDB;
    globalThis.MIL_AIRLIFTER_CIVIL_TYPES = MIL_AIRLIFTER_CIVIL_TYPES;
    globalThis.getMilAirlifterCivilScenarioImgIds = getMilAirlifterCivilScenarioImgIds;
    globalThis.A400_CIVIL_FREIGHT_SCENARIO_IMGIDS = A400_CIVIL_FREIGHT_SCENARIO_IMGIDS;
}
